### ISSUE TITLE
Contour Thresholding

### ISSUE THREAD

**Issue by bakerb845** [usgs/shakemap#1004]
This appears related to the repeated labels for contours issue.  But more to the point is there a way to threshold contours to remove these seemingly superfluous lines?

![intensity_overlay](https://user-images.githubusercontent.com/8157001/65070221-73ca7980-d949-11e9-98ba-58363eb658fc.png)
![pgv](https://user-images.githubusercontent.com/8157001/65070233-7a58f100-d949-11e9-97b5-e693e801b3bd.jpg)

**Comment by bakerb845** [comment]
I pulled the latest/greatest shakemap which fixed the precision in the contour labels.  However, I am still wondering if there is a way to threshold the contours so that values of less than, say, 0.1, are not plotted?

![pgv](https://user-images.githubusercontent.com/8157001/66213892-dcba2d00-e67d-11e9-9831-c7e084d4f90b.jpg)

**Comment by cbworden** [comment]
This is kind of tricky. The very small ground motions are not particularly well constrained. But to set a minimum, you would have to have a different value for each IMT (PGA, PGV, SA at different periods), and what works for one earthquake won't necessarily work for another. You could end up with just one contour, or no contours at all. If you cut the contours off at some arbitrary value, then the user doesn't know if the ground motions fall any further, of if the lowest contour represents a minimum. So I don't know. Others can weigh in and we'll try to implement something that works.

**Comment by emthompson-usgs** [comment]
No response in over 2 years. Closing.
