### ISSUE TITLE
gmpe_sets + model.conf

### ISSUE THREAD

**Issue by bakerb845** [usgs/shakemap#1005]
In model.conf I am entering: 
   # gmpe = active_crustal_nshmp2014
   gmpe = CY14
however, I appear to be getting the default active_crustal_nshmp2014 GMPE.  It appears that I can simply go into gmpe_sets.conf and override the active_crustal_nshmp2014 values to conform with CY14 but that seems a little hackish.
  
#40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
conda 4.6.14

**Comment by cbworden** [comment]
There is no default. If you are getting active_crustal_nshmp2014 then it is being set somewhere. Parameters set in a model.conf file in the event's "current" directory will override those set in the profile's model.conf (e.g., ~/shakemap_profiles/<profile_name>/install/config/model.conf). If there is no model.conf in the event's "current" directory, then parameters set in model_select.conf (in the event's "current" directory) will override those set in the profile's model.conf. If neither of those files exists, the system uses what is set in the profile's model.conf. If the gmpe parameter is not set in one of those three places, the module "assemble" will throw an error.

If you change model.conf (or any of several other config files), the system will want you to run the module "assemble" before you run "model". model never directly looks at any of the config or data files -- it only reads the output of assemble.

**Comment by bakerb845** [comment]
Ahh, the pound sign was supposed to indicate that was commented out and I wanted to only use CY14.  I didn't realize this was markdown. Sorry.

The key here is that I don't want to put a model.conf in my current directory.  I'd like to set gmpe = CY14 in shakemap_profiles/default/install/model.conf.  I see what you are saying - if I create an event like

sm_create uu60314012

then 

more uu60314012/current/model.conf

I get

[gmpe_sets]
    [[gmpe_uu60314012_custom]]
        gmpes = active_crustal_nshmp2014,
        weights = 1.0,
        weights_large_dist = None
        dist_cutoff = nan
        site_gmpes = None
        weights_site_gmpes = None
[modeling]
    gmpe = gmpe_uu60314012_custom
    mechanism = ALL
    ipe = VirtualIPE
    gmice = WGRW12
    ccf = LB13

This must be overriding shakemap_profiles/default/install/model.conf as you noted.  Is there a way to prevent sm_create from doing this?

**Comment by cbworden** [comment]
There isn't an option like that for sm_create right now. It's mostly set up to "clone" an event from ComCat, so we usually want to get the GMPE info from the original. The easiest thing to do is just delete the event-specific model.conf or model-select.conf.

**Comment by bakerb845** [comment]
Okay.  Deleting that local model.conf made the difference.  I'll close this.  Thank you!
