### ISSUE TITLE
DbConnect::connect: couldn't connect: at ./mktables 

### ISSUE THREAD

**Issue by Liu-Richard** [usgs/shakemap#1030]
Please describe your issue here:
when I built shakemap-3.5:https://vault.gps.caltech.edu/repos/products/shakemap/tags/release-3.5/

and ./mktables in bin directory

an error occures:

DbConnect::connect: couldn't connect: at ./mktables line 66.
database=shakemap:  at ./mktables line 66.
DbConnect::connect: unable to connect to a database, trying again... at ./mktables line 66.

I  have installed mysql  ,perl-DBD-mysql/perl-DBI  and complete the configuration of config/mydb.conf   config/db.conf   pw/passwords

anyone can give a good suggestion to solve it ? thanks

**Comment by emthompson-usgs** [comment]
This is the repository for ShakeMap 4.0, which is a complete re-write of the ShakeMap code and you are referencing the prior generation (ShakeMap 3.5) which shares almost no code with the newer version. My suggestion is to try to update to the new and improved version of ShakeMap that is hosted here. 

The only person that is capable of helping you with ShakeMap 3.5 is @cbworden but I'm not sure if he is actually willing to support that code anymore (it is a lot of work!), and also I think he is on vacation and probably won't see this bug report for some time. Another benefit of ShakeMap 4.0 is that there are **3 times** as many developers actively involved in the project and so response time for questions and bug reports will be much faster.

**Comment by cbworden** [comment]
Eric is correct about pretty much everything. ShakeMap v4 is the only version that anyone should install. We are discontinuing support for ShakeMap v3.5. The only reason we still have the SVN repo at vault.caltech is that we very, very occasionally need to make a fix for one of the established installations that haven't converted to v4 yet. All new installations of ShakeMap should use the version here, and all existing installations are encouraged to switch over as soon as possible, as v3.5 is at EOL. ShakeMap v4 is easy to install and we are able to support it, as Eric said, with multiple developers. See the wiki for installation and testing instructions:

https://github.com/usgs/shakemap/wiki

The full documentation and a list of important references are here:

http://usgs.github.io/shakemap/manual4_0/title_page.html

Again, ShakeMap v4 is the only ShakeMap that anyone should be running: it has many improvements, a completely new interpolation scheme, and new and better products. ShakeMap v3.5 is guaranteed to fail as soon as someone changes Perl or one of the dependent libraries in an incompatible way, and at that point we will completely retire it.
