### ISSUE TITLE
about sm_create 

### ISSUE THREAD

**Issue by cuijwyn** [usgs/shakemap#1042]
I want to run shakemap on win10 python3.7 anaconda , while i run sm_create, I get information: D:\Anaconda3\lib\site-packages\rasterio\__init__.py:216: NotGeoreferencedWarning: Dataset has no geotransform set. The identity matrix may be returned.
  s = DatasetReader(path, driver=driver, **kwargs). 
how to resolve.
                       thanks

**Comment by emthompson-usgs** [comment]
While we hope to support ShakeMap on Windows OS in the near future, we currently do not, as explained in the README in the "Installation and Dependencies" and also in the Installation section of the Wiki [here](https://github.com/usgs/shakemap/wiki/Installation).
