### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by ZhangHCFJEA** [usgs/shakemap#1044]
Please describe your issue here:
Hi all, I try to install ShakeMap in my Mac, but I failed -_-,  followings are the errors:
--------------------------------------------------------------------------
ERROR: Command errored out with exit status 1:
     command: /Users/zhang/anaconda3/envs/shakemap/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/zhang/shakemap_src/setup.py'"'"'; __file__='"'"'/Users/zhang/shakemap_src/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/zhang/shakemap_src/
    Complete output (25 lines):
    running develop
    running egg_info
    writing shakemap.egg-info/PKG-INFO
    writing dependency_links to shakemap.egg-info/dependency_links.txt
    writing top-level names to shakemap.egg-info/top_level.txt
    reading manifest file 'shakemap.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'shakemap.egg-info/SOURCES.txt'
    running build_ext
    building 'shakemap.c.pcontour' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/zhang/anaconda3/envs/shakemap/include -arch x86_64 -I/Users/zhang/anaconda3/envs/shakemap/include -arch x86_64 -Ishakemap/c -I/Users/zhang/anaconda3/envs/shakemap/lib/python3.6/site-packages/numpy/core/include -I/Users/zhang/anaconda3/envs/shakemap/include/python3.6m -c shakemap/c/pcontour.c -o build/temp.macosx-10.7-x86_64-3.6/shakemap/c/pcontour.o -O3
    In file included from shakemap/c/pcontour.c:626:
    In file included from /Users/zhang/anaconda3/envs/shakemap/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/zhang/anaconda3/envs/shakemap/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /Users/zhang/anaconda3/envs/shakemap/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:
    /Users/zhang/anaconda3/envs/shakemap/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    1 warning generated.
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/zhang/anaconda3/envs/shakemap/include -arch x86_64 -I/Users/zhang/anaconda3/envs/shakemap/include -arch x86_64 -Ishakemap/c -I/Users/zhang/anaconda3/envs/shakemap/lib/python3.6/site-packages/numpy/core/include -I/Users/zhang/anaconda3/envs/shakemap/include/python3.6m -c shakemap/c/contour.c -o build/temp.macosx-10.7-x86_64-3.6/shakemap/c/contour.o -O3
    gcc -bundle -undefined dynamic_lookup -L/Users/zhang/anaconda3/envs/shakemap/lib -arch x86_64 -L/Users/zhang/anaconda3/envs/shakemap/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/shakemap/c/pcontour.o build/temp.macosx-10.7-x86_64-3.6/shakemap/c/contour.o -lm -o /Users/zhang/shakemap_src/shakemap/c/pcontour.cpython-36m-darwin.so
    building 'shakemap.c.clib' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/zhang/anaconda3/envs/shakemap/include -arch x86_64 -I/Users/zhang/anaconda3/envs/shakemap/include -arch x86_64 -I/Users/zhang/anaconda3/envs/shakemap/lib/python3.6/site-packages/numpy/core/include -I/Users/zhang/anaconda3/envs/shakemap/include/python3.6m -c shakemap/c/clib.c -o build/temp.macosx-10.7-x86_64-3.6/shakemap/c/clib.o -O3 -fopenmp
    clang: error: unsupported option '-fopenmp'
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/zhang/anaconda3/envs/shakemap/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/zhang/shakemap_src/setup.py'"'"'; __file__='"'"'/Users/zhang/shakemap_src/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`
-----------------------------------------------------------------------------
What can I do to fix this?

**Comment by cbworden** [comment]
Yeah, something has changed with gcc, but I'm not sure what. Try editing setup.py and removing the -fopenmp from everywhere in the file. Then run "python setup.py build_ext --inplace" and see if it works. Let us know what happens.

**Comment by ZhangHCFJEA** [comment]
Great thanks! @cbworden 
I tried again as you suggested, it worked!
