### ISSUE TITLE
A process in the process pool was terminated abruptly while the future was running or pending.

### ISSUE THREAD

**Issue by mlmarius** [usgs/shakemap#1048]
```
(shakemap) shake@4a5d76411581:~/shakemap_src$ python setup.py --version
4.0.2+239.g4a699f17
(shakemap) shake@4a5d76411581:~/shakemap_src$ uname -v
#1 SMP Thu Oct 17 19:31:58 UTC 2019
(shakemap) shake@4a5d76411581:~/shakemap_src$ conda --version
conda 4.8.2
(shakemap) shake@4a5d76411581:~/shakemap_src$
```

I've followed the documentation for installing Shakemap4 and now am attempting to run the example. I've also built a docker image for my run: mlmarius/shakemap. In this image I do the following

```
docker -i -t mlmarius/shakemap:latest
condo activate shakemap
sm_create ci3144585
```

If I don't do `shake ci3144585 select` I start getting warnings requiring me to use --force from then on so I would appreciate more info on what select actually does and why I need to run it

```
shake ci3144585 select
shake ci3144585 assemble model contour mapping
```

here it warns me about downloading some stuff. Can I force it do download this stuff before my first runs seeing as how I'm planing to have this as a docker container ?

this is my result:

```
(shakemap) shake@4a5d76411581:~$ shake ci3144585 assemble model contour mapping
INFO -- 2020-04-04 07:23:10 -- shake.main -- Running command assemble
Please enter a comment for this version.
comment: test
INFO -- 2020-04-04 07:23:14 -- shake.main -- Finished running command assemble: Elapsed 4.37 secs
INFO -- 2020-04-04 07:23:14 -- shake.main -- Running command model
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Extent and resolution of shakemap results in too many grid points. Adjusting resolution...
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Longitude span: 8.500000
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Latitude span: 7.016667
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Current dx: 0.008333
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Current dy: 0.008333
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Current number of grid points: 860703
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Max grid points allowed: 500000
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Updated dx: 0.016667
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Updatd dy: 0.016667
INFO -- 2020-04-04 07:23:14 -- model._adjustResolution -- Updated number of grid points: 215642
WARNING -- 2020-04-04 07:23:20 -- warnings._showwarnmsg -- /opt/conda/envs/shakemap/lib/python3.6/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: http://naciscdn.org/naturalearth/10m/physical/ne_10m_ocean.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
INFO -- 2020-04-04 07:26:46 -- shake.main -- Finished running command model: Elapsed 211.94 secs
INFO -- 2020-04-04 07:26:46 -- shake.main -- Running command contour
INFO -- 2020-04-04 07:26:50 -- shake.main -- Finished running command contour: Elapsed 3.74 secs
INFO -- 2020-04-04 07:26:50 -- shake.main -- Running command mapping
WARNING -- 2020-04-04 07:26:52 -- warnings._showwarnmsg -- /opt/conda/envs/shakemap/lib/python3.6/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: http://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_1_states_provinces_lines.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
WARNING -- 2020-04-04 07:26:57 -- warnings._showwarnmsg -- /opt/conda/envs/shakemap/lib/python3.6/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: http://naciscdn.org/naturalearth/10m/cultural/ne_10m_admin_0_countries.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)
WARNING -- 2020-04-04 07:27:01 -- warnings._showwarnmsg -- /opt/conda/envs/shakemap/lib/python3.6/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: http://naciscdn.org/naturalearth/10m/physical/ne_10m_lakes.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)

CRITICAL -- 2020-04-04 07:27:22 -- shake.main --
Earthquake: M6.7 1km NNW of Reseda, CA
Host: 4a5d76411581
Event ID: ci3144585
Exception: A process in the process pool was terminated abruptly while the future was running or pending.
Stack Trace:   File "/home/shake/shakemap_src/bin/shake", line 305, in main
    obj.execute()
  File "/home/shake/shakemap_src/shakemap/coremods/mapping.py", line 358, in execute
    list(results)
  File "/opt/conda/envs/shakemap/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/opt/conda/envs/shakemap/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/opt/conda/envs/shakemap/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/conda/envs/shakemap/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
```
Can someone help me to get it running ?

**Comment by cbworden** [comment]
We've only begun to start working with Docker ourselves, so I'm not sure we can be much help. The Natural Earth features that get downloaded on the first run of mapping may get stored in different places on different systems, but on my mac, they are in:

~/.local/share/cartopy/shapefiles/natural_earth/physical/

You could try unpacking them there and see if that will work. I don't know if you want to have them within the image, or residing on the host, though. Our thinking is that configs and data files should probably be on the host. Whether these should be bind mounts or volumes remains an open question. The same issue applies to the the Vs30 and topography grids.

If your other issue persists, set max_workers in model.conf to 0 (zero), so we can get a useful diagnostic. The multiprocessing error messages are not generally helpful.

**Comment by mlmarius** [comment]
Thanks for the reply. As per your recommendation, I went ahead and mounted the cartopy dependencies from the host so now it's not downloading them on each run anymore. I've also set max_workers = 0 in model.conf but unfortunately I keep bumping into the same error. I've also added vim to my image so edits can be easily made from within the image. If you would like to run my environment I guess `docker run -i -t mlmarius/shakemap` should drop you into the appropriate conda environment ready to go. Any other suggestions ?

**Comment by cbworden** [comment]
Sorry, I misread your first message. It looks like model worked fine, so you don't need to set max_workers=0 in model.conf. It looks like the problem is in mapping, so you want to set max_workers=0 in products.conf. That will disable the threading there and (hopefully) give better diagnostic messages.

**Comment by cbworden** [comment]
So when I followed my own suggestion above, your container worked for me. My guess on what's happening is that the first time through, something still needs to download, and while one thread tries to get it, the others fail. So do as I suggest above (max_workers=0 in products.conf) and then run mapping on the event and see what downloads. Make sure that is part of the data in your Natural Earth directory, and then your subsequent runs should work fine, and you can remove the max_workers=0 line from products.conf.
