### ISSUE TITLE
During on the fail of test(done at 64%), 'Fatal Python error : Segmentation fault' keep occurring.

### ISSUE THREAD

**Issue by qsedfrfjskasd** [usgs/shakemap#1052]
Please describe your issue here:

Hello, I am a linux user. I installed the shakemap(4.0)
And, I've been tried several tests of installation, but they stopped at the same point of the process.  
![주석 2020-04-14 165117](https://user-images.githubusercontent.com/63638769/79204852-2929c500-7e78-11ea-8a52-6d3ec6528ccc.jpg)

Just in case, I tried some command like a ' sm_create', It was also fail.
![image](https://user-images.githubusercontent.com/63638769/79208574-2d0c1600-7e7d-11ea-9272-3b31aef2e5bb.png)

Also,  I referred similar issue#963 and set the 'max-workers' to 0. 

This is a terminal log, After I try ' py.test tests/shakemap/coremods/model_test.py
![image](https://user-images.githubusercontent.com/63638769/79207918-4d87a080-7e7c-11ea-9c4c-e12e6115aa54.png)
![image](https://user-images.githubusercontent.com/63638769/79207963-609a7080-7e7c-11ea-888d-7e25efeb17a0.png)

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version` : 3.6
    - `uname -v` 
    - `conda 4.8.2 version`

**Comment by cbworden** [comment]
I've never seen the first problem before. I suspect there is some compatibility problem with some of your installed packages. I would recommend removing the conda environment, doing "conda clean --all", then pulling the latest version of the ShakeMap repo, and then redoing the install. If you still have problems, you might try reinstalling with "bash install.sh -p 3.7" (or 3.8) to get a newer version of python. Though we've had no problems with 3.6, your OS may have conflicts with it.

The second problem seems not to be a problem -- the warning about downloading the Natural Earth ocean file is just a warning and the download should complete after a minute or two -- depending on how good your internet connection is.

Can you run "uname -v" so we can know what OS you are using?

**Comment by qsedfrfjskasd** [comment]
Hello, Thanks you for suggesting specific solutions. 

Though, I couldn't finish the tests(through the both of ver. 3.7 & 3.8), After I execute "conda clean --all"

As your suggestion, I attach the result of checking the OS. 
![uname_v](https://user-images.githubusercontent.com/63638769/79414988-12ee4700-7fe7-11ea-8f5b-0a165445ae14.jpg)

**Comment by cbworden** [comment]
Okay, I'm still not sure, and uname -v didn't give much info*. Could you run "uname -a" and report back? Also run "date -u".

*The one thing I see is that you system date is quite old -- I'm not sure what that means in terms of the OS and it's version, or what packages will run on it and how. But ShakeMap v4 didn't even exist in 2017, so there's no telling what could have changed in the OS, multiprocessing, and packages since then. If you can upgrade to the latest version of your OS, then do a clean reinstall of ShakeMap, I'd recommend it. Even if that means running in a virtual machine.

**Comment by qsedfrfjskasd** [comment]
These are the information showed up, After I executed the commands.
![image](https://user-images.githubusercontent.com/63638769/79722750-94afde80-831f-11ea-84ed-85e1137157fe.png)

As your suggestion, I changed OS, and reinstalled shakemap4.0.
Then, the test just went on smoothly, Thank you very much.
