### ISSUE TITLE
Production of 3D shakemap

### ISSUE THREAD

**Issue by NooshinHadidian** [usgs/shakemap#1057]
Please describe your issue here:
All Dear

Would you please guide me in the field of 3D shake maps production process and related codes in shakeMap 4? Thanks
---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
I'm not sure what you mean by 3D ShakeMaps. Can you elaborate on what you are trying to do or what is not working?
