### ISSUE TITLE
A very basic question: If we already knew MMI distribution of an event, how could I generate a contour map by Shakemap? Can someone provide a tutorial?

### ISSUE THREAD

**Issue by ZhangHCFJEA** [usgs/shakemap#1058]
Please describe your issue here:
Hi all,
I'm a beginner user of Shakemap, and already installed the software. But I found it may be a little hard for me to start exploring after I read the whole Wiki. So my question is quite simple: suppose we already have the seismic intensity calculations (e.g. MMI) from stations of an event, how can we generate MMI contour map based on these data (and also vs30 grid)? Can someone provide a useful tutorial? Many thanks.
---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
I'm not sure what you are asking. Have you computed the MMI field from stations, and want to use that field in ShakeMap, or are you just asking how to include station data in the computations? The first can be done, if the data are provided in CSV form, but this is a rather advanced usage and doesn't generally require ShakeMap at all. For the second, the example and test events have a number of examples of the format for seismic and macroseismic data. You should also have a look at the ShakeMap 4 Manual (linked at the top of the main ShakeMap page on GitHub). See the section on input formats.

**Comment by ZhangHCFJEA** [comment]
Hi Bruce, thanks. Actually I mean I already have MMI field of an event, then I try to use Shakemap to produce a contour map. I know this can be done by GMT directly under Kriging interpolation, but I'm not sure how to make the site-effect correction by using the vs30 grid. So I try to understand how this achieved in Shakemap. According to my understanding, I may need to prepare some input files, but if there is a tutorial that will be much better.

**Comment by cbworden** [comment]
ShakeMap won't apply site corrections to a precomputed field. The assumption is that such an input field was computed with a specialized modeling system, and that the site terms are already included. We have no way to separately apply site effects in any event. All of our site effects come from the GMPE predictions that ShakeMap computes when it is doing the modeling. There are no well established models of MMI site effects, in any event. Essentially, when you use a precomputed field, ShakeMap just passes it through without modification. It is then available to the modules that do mapping, contouring, etc. You can't have it both ways -- either ShakeMap does the modeling, or you do. If you do it, ShakeMap assumes that those are the results you want, and it just makes the output products.

**Comment by ZhangHCFJEA** [comment]
Hi Bruce. Thank you for your detailed explanation. Now I know it might be unlikely to achieve my needs by using Shakemap. Also, another question of mine is, as recorded stations are limited and uneven distribution, there must be a certain number of GMPE predictions, then how to combine these two kinds of data to generate products? and do we also need to consider site effect correction for these GMPE predictions? and how to do it?

**Comment by emthompson-usgs** [comment]
Hi @ZhangHCFJEA, the details and math of how the GMPE predictions are combined with observations are described here:
https://doi.org/10.1785/0120170201
Site effects are are routinely (but not ubiquitously) modeled in GMPEs, and so we do not have to treat site effects in a special manner outside of the GMPE evaluation.

**Comment by ZhangHCFJEA** [comment]
Hi Eric, I'm very glad to receive you and Dr. Worden's reply, I've downloaded your paper and will read it carefully. I hope I can use your spatial and spectral interpolation method in my code. Many thanks again.

**Comment by emthompson-usgs** [comment]
Thanks for your interest. Also, note that you could look for clues about how we do the calculation in ShakeMap, but it is obscured by a bunch of other unrelated code so that may not be the best choice. There is a very simple python script in the esup for that paper that would likely be more useful if you are trying to develop your own implementation.

**Comment by cbworden** [comment]
Also note that this section of the manual goes through more details of the ShakeMap implementation of the interpolation method. It may be helpful in understanding the code Eric referred to:
http://usgs.github.io/shakemap/manual4_0/tg_processing.html
