### ISSUE TITLE
mapping module fails when max_workers > 0

### ISSUE THREAD

**Issue by cbworden** [usgs/shakemap#1071]
Please describe your issue here:

On some systems, when the max_workers parameter in products.conf (NOT model.conf) is set to a value > 0, the process fails with difficult-to-interpret errors. (These errors often look like a projection not being found, or a file not being available.)

max_workers in products.conf should default to 0; any systems that have this set to the current default, or manually set to something other than 0 should consider setting it to 0. Any other value has the potential to cause intermittent failures. I will submit a PR changing the default to 0 shortly, but I'll leave this issue up until everyone has upgraded.

The problem is that some of the conda packages we use are not thread-safe or even, seemingly, multi-process-safe. So we can't safely spin off multiple processes to make the various maps. Hopefully the people who maintain these packages will eventually make them more tolerant of multi-process use, but I'm not holding my breath. I will try at some point to work around the errors, but it may not be possible. And my development system is MacOS, where these problems don't seem to show up.

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by merdo8888** [comment]
Dear Bruce,
I met the same problems, and I want to know how to set max_workers=0 in products. conf .
Thanks

**Comment by cbworden** [comment]
I think you have a more recent installation, so it is unlikely (though possible) that you are experiencing this problem. Some people have recently reported a problem in which Cartopy was unable to download the some Natural Earth geography files. We are hoping that this is just a transient problem and will resolve soon. Otherwise it may require an upgrade of Cartopy when they figure out the problem.

Can you post the errors you are seeing so we can tell what the nature of your problem is?

**Comment by merdo8888** [comment]
Here is the error message, I think there is an error in downloading the file from Natural Earth geography files. Thanks.

DownloadWarning: Downloading: https://naciscdn.org/naturalearth/10m/physical/ne_10m_ocean.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)

and here is the full code and output:
(shakemap) houwenlong@koubuns-MBP ~ % shake ci3144585 model
INFO -- 2021-09-15 09:52:43 -- shake.main -- Running command model
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Extent and resolution of shakemap results in too many grid points. Adjusting resolution...
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Longitude span: 8.500000
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Latitude span: 7.016667
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Current dx: 0.008333
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Current dy: 0.008333
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Current number of grid points: 860703
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Max grid points allowed: 500000
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Updated dx: 0.016667
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Updatd dy: 0.016667
INFO -- 2021-09-15 09:52:43 -- model._adjustResolution -- Updated number of grid points: 215642
WARNING -- 2021-09-15 09:52:46 -- warnings._showwarnmsg -- /opt/anaconda3/envs/shakemap/lib/python3.8/site-packages/cartopy/io/__init__.py:260: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/10m/physical/ne_10m_ocean.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)

CRITICAL -- 2021-09-15 09:52:47 -- shake.main -- 
Earthquake: M6.7 1km NNW of Reseda, CA
Host: koubuns-MBP
Event ID: ci3144585
Exception: <urlopen error [Errno 8] nodename nor servname provided, or not known>
Stack Trace:   File "/Users/houwenlong/Downloads/shakemap-4.0.5/bin/shake", line 323, in main
    obj.execute()
  File "/Users/houwenlong/Downloads/shakemap-4.0.5/shakemap/coremods/model.py", line 251, in execute
    landmask = self._getLandMask()
  File "/Users/houwenlong/Downloads/shakemap-4.0.5/shakemap/coremods/model.py", line 1551, in _getLandMask
    oceans = shpreader.natural_earth(category='physical',
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/site-packages/cartopy/io/shapereader.py", line 295, in natural_earth
    return ne_downloader.path(format_dict)
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/site-packages/cartopy/io/__init__.py", line 222, in path
    result_path = self.acquire_resource(target_path, format_dict)
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/site-packages/cartopy/io/shapereader.py", line 350, in acquire_resource
    shapefile_online = self._urlopen(url)
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/site-packages/cartopy/io/__init__.py", line 261, in _urlopen
    return urlopen(url)
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/anaconda3/envs/shakemap/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)

**Comment by cbworden** [comment]
Yeah, this looks like the NE download problem, not the max_workers problem. Can you let us know if it has resolved for you (just run the exact same event again)? We are not seeing it in our tests, but that's not always comprehensive.

**Comment by merdo8888** [comment]
Not working when I run the same code ($shake ci3144585 shakemap), still showing the same error

**Comment by cbworden** [comment]
Yes, I see now that their server is still down: https://www.naturalearthdata.com/ (note the red band at the top). I think your options are 1) Wait for the server to be fixed; 2) Wait for a new version of Cartopy that uses the S3 servers; or 3) Download the correct files yourself from the S3 server and unpack them in the correct place for Cartopy to find them. In my system, that was `~/.local/share/cartopy/shapefiles/natural_earth/cultural` and `./.local/share/cartopy/shapefiles/natural_earth/physical`, where `cultural` has
```
ne_10m_admin_0_countries.dbf
ne_10m_admin_0_countries.shp
ne_10m_admin_0_countries.shx
ne_10m_admin_1_states_provinces_lines.dbf
ne_10m_admin_1_states_provinces_lines.shp
ne_10m_admin_1_states_provinces_lines.shx
``` 
and `physical` has
```
ne_50m_coastline.dbf
ne_50m_coastline.shp
ne_50m_coastline.shx
ne_50m_ocean.dbf
ne_50m_ocean.shp
ne_50m_ocean.shx
ne_50m_land.dbf
ne_50m_land.shp
ne_50m_land.shx
ne_10m_ocean.dbf
ne_10m_ocean.shp
ne_10m_ocean.shx
ne_10m_lakes.dbf
ne_10m_lakes.shx
ne_10m_lakes.shp
ne_110m_coastline.dbf
ne_110m_coastline.shp
ne_110m_coastline.shx
ne_10m_coastline.dbf
ne_10m_coastline.shp
ne_10m_coastline.shx
```
I don't know if you actually need all three resolutions in physical, but it can't hurt.

Options 1 and 2 are probably easier, but I don't know how long you would have to wait. And my system is MacOS 10.15.7, so I don't know if your location for the NE files will be the same. You might have to do some searching.

**Comment by cbworden** [comment]
Actually, Option 2 from the above post looks like it has already happened:
https://scitools.org.uk/cartopy/docs/latest/reference/generated/cartopy.io.shapereader.NEShpDownloader.html
Try forcing an update of cartopy in your ShakeMap environment and then run your example again.

**Comment by merdo8888** [comment]
I have tried option 3, and it did not work. I think there is an initialization program in cartopy to download the shapefile from the natural earth data server. And I want to know how to update the cartopy in the shakemap environment. Thanks.

   -- warnings._showwarnmsg -- /opt/anaconda3/envs/shakemap/lib/python3.8/site-packages/cartopy/io/init.py:260: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/10m/physical/ne_10m_ocean.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)

**Comment by cbworden** [comment]
Try:
```
$ conda activate shakemap

$ conda update cartopy
```

**Comment by merdo8888** [comment]
I have changed the server address from https://naciscdn.org/naturalearth/10m/physical/ne_10m_ocean.zip to https://naturalearth.s3.amazonaws.com/10m_physical/ne_10m_ocean.zip in the cartopy program (shapereader.py).

And it works now! Thanks.
