### ISSUE TITLE
 Earthquake map generation error

### ISSUE THREAD

**Issue by reywlady** [usgs/shakemap#1081]
Good morning, I am having trouble processing an earthquake in the mapping module.

This error can occur if I execute the shake commands for the same earthquake, same datas, successively.

We would appreciate your guide to solve it.

ERROR 1: PROJ: proj_as_wkt: SQLite error on SELECT table_name, auth_name, code, name, deprecated, is_alias FROM (SELECT table_name, auth_name, code, name, deprecated, 0 as is_alias FROM object_view WHERE ((table_name IN ('geodetic_datum') )) UNION SELECT ov.table_name AS table_name, ov.auth_name AS auth_name, ov.code AS code, a.alt_name AS name, ov.deprecated AS deprecated, 1 as is_alias FROM object_view ov JOIN alias_name a ON ov.table_name = a. table_name AND ov.auth_name = a.auth_name AND ov.code = a.code WHERE ((ov.table_name IN ('geodetic_datum')))) ORDER BY deprecated, is_alias, length (name), name: database disk image is malformed

---------- - ------------  - ------------- ---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`
-------------------------------------
python setup.py version

running version
keywords are unexpanded, not using
got version from VCS {'version': '4.0.2+234.g197a5394', 'full-revisionid': '197a5394e7bc3813fa6a3bea9512530fb4f8910e', 'dirty': False, 'error': None, 'date': '2020-03-19T14:51:35-0600'}
Version: 4.0.2+234.g197a5394
 full-revisionid: 197a5394e7bc3813fa6a3bea9512530fb4f8910e
 dirty: False
 date: 2020-03-19T14:51:35-0600

--------------
uname -v

#56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020

---------------
conda --version

conda 4.8.2

**Comment by reywlady** [comment]
nothing

**Comment by cbworden** [comment]
In products.conf set "max_workers = 0".
