### ISSUE TITLE
Missing cities and wrong scalebar length

### ISSUE THREAD

**Issue by tsonne** [usgs/shakemap#1088]
I've posted two issues in the `impactutils` repo about this, but maybe the Shakemap repo is mostly affected and gets seen by more people, who might be wondering about these details.

* https://github.com/usgs/earthquake-impact-utils/issues/134
* https://github.com/usgs/earthquake-impact-utils/issues/135

The static maps from Shakemap can lack some cities if there are few (<20 ?) cities in the plotted region due to some inequality signs in the code which exclude cities on the southern and western edge of the box of all cities within a map region. Can happen if your country is small and isolated (sparse islands in oceans) or barely populated, then you'll be missing some towns you'd expect to be there.

The map scalebar doesn't show the correct length except at the Equator, while it is wrong by a factor of 2 at latitude 60 deg. I've posted a suggested solution in the `impactutils` git repo as I thought it's more appropriate there. The incorrectly scaled scalebar can make it look like there's about twice as much space between cities in the far north/south.

**Comment by cbworden** [comment]
Thanks for filing the bug reports and for finding solutions. We'll have a look and update the code ASAP.

**Comment by emthompson-usgs** [comment]
Well, we hardly met the "ASAP" criteria, but I did just finally fix these issues in impactutils. We (me, @cbworden, @mhearne-usgs) need to be better at resolving these bugs in a timely manner going forward!
