### ISSUE TITLE
shakemap installation failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by hadighasemi** [usgs/shakemap#1089]
Please describe your issue here:

Hi All,

I am trying to install shakemap on ubuntu 18.04 machine, and am getting the below error. Any help/suggestions would be greatly appreciated!

Kind Regards
Hadi

**required info**
uname -v
#49~18.04.2-Ubuntu SMP Wed Aug 26 16:29:02 UTC 2020

conda --version
conda 4.3.30

**Error message:**
Installing shakemap...
Obtaining file:///home/hadi/shakemap_src
    ERROR: Command errored out with exit status 1:
     command: /home/hadi/anaconda3/envs/shakemap/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/hadi/shakemap_src/setup.py'"'"'; __file__='"'"'/home/hadi/shakemap_src/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wpwq0on3
         cwd: /home/hadi/shakemap_src/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/hadi/shakemap_src/setup.py", line 88, in <module>
        ext_modules=cythonize(ext_modules)
      File "/home/hadi/anaconda3/envs/shakemap/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 972, in cythonize
        aliases=aliases)
      File "/home/hadi/anaconda3/envs/shakemap/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/home/hadi/anaconda3/envs/shakemap/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'shakemap/c/pcontour.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
Hi Hadi,

Have you looked to see if the file in question (shakemap/c/pcontour.pyx) is there? If it is not, then your clone of the repo failed somehow. If it is, then something failed earlier when you ran "bash install.sh" in the repo directory. I can't think of any way that the cython compiler wouldn't be able to find that file.

**Comment by hadighasemi** [comment]
Hi Bruce,

Thanks heaps! all working now, I had to also replace "conda activate" with "source activate", and set default python version to 3.6 in the install shell script. 

Best,
H
