### ISSUE TITLE
Add data reference information to info.json

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#1102]
Please describe your issue here:

The StationList object now supports optional reference information, which should be extracted into a "data references" section in info.json.

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
This is basically done. If we ever start adding station reference info, we just need to have it rendered on the web.
