### ISSUE TITLE
Providing DYFI input to Shakemap v4

### ISSUE THREAD

**Issue by mlmarius** [usgs/shakemap#1118]
I have no knowledge of Shakemap. I have a data source containing some DYFI. I have lat, lon and decimal values in there and I would like to make them available to Shakemap. I can format and dump the data into a file but I can't figure out how this data should be formated. A small example showing how to write a few data rows to a file and then how to persuade Shakemap to include them in its processing pipelines would be great.

**Comment by cbworden** [comment]
The input data formats are described in detail here: http://usgs.github.io/shakemap/manual4_0/sg_input_formats.html
I would not recommend running ShakeMap as a casual effort, however. There are many factors to consider and a lot of configuration options will affect the results you obtain. If there is a specific event of interest, it may be one that we have already processed as part of our ShakeMap Atlas. Or if the event is of general interest (there was damage, casualties, considerable data), it may be something we could add to the Atlas. If you can share more information, we may be able to help you.

**Comment by mlmarius** [comment]
thanks for the reply, @cbworden. I won't be attempting to run it myself. I just want to ship some data in a format that will be usable by ShakeMap. I of course did visit the url kindly provided by you before opening this issue, should have mentioned that, but unfortunately, it's full of scary seismological terms that I don't understand talking about things that I don't have access to. I just have a list of <timestamp, lat, lon, intensity> and would like to pack it in a file that may be used by Shakemap. I don't have things like id, netid, depth, mech, productcode, and whatnot. Is it doable with the data that I currently possess?

**Comment by cbworden** [comment]
It seems like we left this hanging. I'm going to close it, but if you still need help, feel free to reopen and we can see what we can do.
