### ISSUE TITLE
Running shakemap

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1131]
Hi all,
finally I had install shakemap in my computer.
I have seen that my PYTHONPATH environment change only when I activate shakemap and return as before, deactivating shackemap (conda activate shakemap - conda deactivate)
Now, following instruction, I have download the default profile with command

 sm_profile -c default -e

and the output was 

Created profile: Profile: default 
	Install Path: /home/sysop/shakemap_profiles/default/install
	Data Path: /home/sysop/shakemap_profiles/default/data
Retrieving global topo and Vs30 files. This may take a minute...
Done.
Configuring profile to use downloaded topo and vs30 files...
Done.

after, I have try to show what happen with  creation of an example event suggested 

sm_create ci3144585

but some errors appears:

Traceback (most recent call last):
  File "/home/sysop/miniconda/envs/shakemap/bin/sm_create", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/sysop/shakemap_src/bin/sm_create", line 18, in <module>
    from impactutils.io.table import dataframe_to_xml
ModuleNotFoundError: No module named 'impactutils.io.table'

moreover I have try with 

shake -h

and also this report errors

Traceback (most recent call last):
  File "/home/sysop/miniconda/envs/shakemap/bin/shake", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/sysop/shakemap_src/bin/shake", line 87, in <module>
    _classes_ = _get_command_classes(_config_)
  File "/home/sysop/shakemap_src/bin/shake", line 61, in _get_command_classes
    in pkgutil.iter_modules(mod.__path__, mod.__name__ + ".")
  File "/home/sysop/shakemap_src/bin/shake", line 60, in <dictcomp>
    for finder, name, ispkg
  File "/home/sysop/miniconda/envs/shakemap/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sysop/shakemap_src/shakemap/coremods/dyfi.py", line 9, in <module>
    from impactutils.io.table import dataframe_to_xml
ModuleNotFoundError: No module named 'impactutils.io.table'

Where I wrong?

Best regards, 

Sergio

**Comment by SergioT59** [comment]
(shakemap) [sysop@server_seiscomp shakemap_src]$ git show HEAD~1
commit eb95729ccfc6ba86b3b71ed9f6f0d3fe4e134e8f
Merge: 17d7a18 0602e88
Author: C. Bruce Worden <cbworden@users.noreply.github.com>
Date:   Wed Nov 18 15:47:06 2020 -0700

    Merge pull request #1098 from ggann/master
    
    Proposing change of property "cancel_message" to "cancel_content"

(shakemap) [sysop@server_seiscomp shakemap_src]$

**Comment by cbworden** [comment]
Yes, you are using older ShakeMap code with newer versions of the libraries, particularly impactutils.

If you cloned your repo directly from the usgs/shakemap github repo (this is most likely), you can update the code with:

```
$ git pull --rebase origin master
```

If you first forked the usgs/shakemap github repo to your own github repo, and then cloned from that (less likely), you will want to do:

```
$ git remote add upstream https://github.com/usgs/shakemap.git
$ git pull --rebase upstream master
$ git push origin master
```

In either case, you should not have to reinstall. It's possible that you will have to if we've added any dependencies since your version, but I don't know if we have. If you get errors after doing one of the above, let us know.

**Comment by SergioT59** [comment]
with thw first suggestion, I receive:

remote: Enumerating objects: 190, done.
remote: Counting objects: 100% (190/190), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 190 (delta 102), reused 127 (delta 63), pack-reused 0
Ricezione degli oggetti: 100% (190/190), 71.21 KiB | 0 bytes/s, done.
Risoluzione dei delta: 100% (102/102), completed with 22 local objects.
Da https://github.com/usgs/shakemap
 * branch            master     -> FETCH_HEAD
   52ba06e..0a011e0  master     -> origin/master
First, rewinding head to replay your work on top of it...
Fast-forwarded master to 0a011e00560a3d73323f488678cdf44219238246.

**Comment by SergioT59** [comment]
After:

(shakemap) [sysop@server_seiscomp shakemap_src]$ shake -h
usage: shake [-h] [-d] [-q] [-l] [-f] [-c] [-y] [-a] [-v] eventid ...

    Run specified ShakeMap modules.
    

positional arguments:
  eventid        The id of the event to process.
  cmds           The modules to run.

optional arguments:
  -h, --help     show this help message and exit
  -d, --debug    Print all informational messages.
  -q, --quiet    Print only errors.
  -l, --log      Log all output.
  -f, --force    Force the command(s) to run regardless of out of date
                 dependencies.
  -c, --cancel   Cancel shakemap; execute cancel_modules list in shake.conf.
  -y, --dryrun   Print a command line that would be executed if the process
                 was called without this flag, and then exit without other
                 action.
  -a, --autorun  No-op; we are keeping this argument for backward
                 compatibility but it no longer does anything. It is now the
                 default behavior to use the autorun_modules in shake.conf
                 when no modules are specified.
  -v, --version  Print the version of ShakeMap and quit.

Available modules:
    - assemble -- Assemble ShakeMap input data into the shake_data.hdf input
                  file.
    - associate -- Associate amps in the database with the event, and write
             XML data file to the event's current directory.
    - augment -- Incorporate additional content into the shake_data.hdf input
                 file.
    - contour -- Generate contours of all IMT values from the
                 shake_result.hdf output file.
    - coverage -- Create JSON coverage(s) of the ground motion layers.
    - dyfi -- Search ComCat for DYFI data and turn it into a ShakeMap data file.
    - Module to raise an exception for testing purposes.
    - gridxml -- Create grid.xml and uncertainty.xml files from shake_result.hdf.
    - history -- Output the version history of an event.
    - info -- Extract info.json from shake_result.hdf and write it as a file.
    - kml -- Generate KML/KMZ files for ShakeMap.
    - mapping -- Generate maps of the IMTs found in shake_result.hdf.
    - model -- Interpolate ground motions to a grid or list of locations.
    - plotregr -- Plot the regression curves from a data file
    - info -- Extract point data from shake_result.hdf and write as CSV file.
    - raster -- Generate GIS raster files of all IMT values from
                shake_result.hdf.
    - rupture -- Generate rupture.json from shake_result.hdf.
    - save - Create backup directory and prep for next ShakeMap map version.
    - select - Parse STREC output, make a GMPE set, create model_select.conf.
    - shape -- Generate shape files of the ground motion parameters
    - sleep -- Sleep for a number of seconds.
    - stations -- Generate stationlist.json from shake_result.hdf.
    - transfer_email - Transfer content via Email.
    - transfer_pdl - Transfer content via PDL to a remote server.
    - transfer_pdl - Transfer content via SCP to a remote server.
    - uncertaintymaps -- Generate maps of the uncertainty of the IMTs
found in shake_result.hdf.

Use "shake help command" to see the options for a specific command.

**Comment by SergioT59** [comment]
Now:
I have some events where the output for shakemap is already create with seiscomp.
This files are in xml format and the header is like:
1) event.xml:
?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE earthquake SYSTEM "earthquake.dtd">
<earthquake id="20201019221534_27_42877_013573_20201023142103" lat="42.8772" lon="13.5733" depth="5.28" mag="2.74893"  and so on;

2) event_dat.xml:
?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE earthquake SYSTEM "stationlist.dtd">
<stationlist created="" xmlns="ch.ethz.sed.shakemap.usgs.xml">
  <station code="IZTMP" name="IZTMP" netid="IZ" source="Perugia" insttype="SS45" lat="43.4545" lon="12.3056">
    <comp name="--.EHE">
      <acc value="0.0001824614" flag="0"/>
      <vel value="0.0000564654" flag="0"/>
      <psa03 value="0.0009274001" flag="0"/>
      <psa10 value="0.0007310496" flag="0"/>
      <psa30 value="0.0005761691" flag="0"/>
    </comp> .... and so one.

Is possible to generate a shakemap with this two files?
Where I can see for understand how do that

**Comment by SergioT59** [comment]
Sorry, the second file is not visible

'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE earthquake SYSTEM "stationlist.dtd">
<stationlist created="" xmlns="ch.ethz.sed.shakemap.usgs.xml">
  <station code="IZTMP" name="IZTMP" netid="IZ" source="Perugia" insttype="SS45" lat="43.4545" lon="12.3056">
    <comp name="--.EHE">
      <acc value="0.0001824614" flag="0"/>
      <vel value="0.0000564654" flag="0"/>
      <psa03 value="0.0009274001" flag="0"/>
      <psa10 value="0.0007310496" flag="0"/>
      <psa30 value="0.0005761691" flag="0"/>
    </comp>
</station>
</stationlist>'

**Comment by SergioT59** [comment]
Sorry, the second file is not visible:

`<?xml` version="1.0" encoding="UTF-8" standalone="yes"?>
`<!DOCTYPE` earthquake SYSTEM "stationlist.dtd">
`<stationlist` created="" xmlns="ch.ethz.sed.shakemap.usgs.xml">
``  <station code="IZTMP" name="IZTMP" netid="IZ" source="Perugia" insttype="SS45" lat="43.4545" lon="12.3056">
``    <comp name="--.EHE">
``      <acc value="0.0001824614" flag="0"/>
``      <vel value="0.0000564654" flag="0"/>
``      <psa03 value="0.0009274001" flag="0"/>
``      <psa10 value="0.0007310496" flag="0"/>
``      <psa30 value="0.0005761691" flag="0"/>
``    </comp>

**Comment by emthompson-usgs** [comment]
So far as I can tell, everything on the ShakeMap side is functioning. The information you are asking about, e.g., how to run ShakeMap for an event, is described in the manual in detail in this section:
http://usgs.github.io/shakemap/manual4_0/sm4_software_guide.html

In conjunction with reading that section of the manual, I suggest you follow the example event instructions in the wiki, which will illustrate the directory structure for creating an event: 
https://github.com/usgs/shakemap/wiki/example-event
It is pretty similar, but not identical to ShakeMap 3.5.

**Comment by SergioT59** [comment]
Thanks for your answer.
I have download the github example (ci3144585) and try to understand how it works.
After understand some error, I had put --force for every command with shake, and finally saw the output... Very very well.

After that I had try with local event, for that I have event.xml and event_dat.xml but it fails.
Understanding the errors and correct the files (maybe for shakemap 3.5), I got the maps.
Thanks and best regards to everybody.

Sergio

**Comment by emthompson-usgs** [comment]
The most common reason that you would need `--force` is that you would need to run the `select` subcommand before proceeding. While it isn't a big deal for testing, it would probably be a bad idea to get in the habit of including the force option. This is a relevant excerpt from the manual:

"`shake` will attempt to assess if a module is being run out of sequence or if its dependencies are out of date. For instance, if a new data file has been added, and the user tries to run the `model` module before re-running the `assemble` module, `shake` will warn the user and quit without running `model`. The user can override this behavior by calling shake with the `--force` option."
