### ISSUE TITLE
Personalized map

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1132]
After obtaining shakepap images, now I would to personalize some header map info.
I have tryed to change parameters in event.xml (the only that I have locate with parameter) but they aren't writed in maps header.
Where I had to see?

Best regards,
Sergio

**Comment by cbworden** [comment]
This depends on what you would like to do. If you would like the header to be in a language other than English, we have a set of files that will do much of the translation. Look in <shakemap>/shakemap/data/mapping where you will find a number of files called "map_strings.*". So far we have English (various nations), Spanish, French (Canadian), and two forms of Chinese. If one of these doesn't work for you, you can make your own (instructions are in the files). For instance, if you wanted the maps in Italian, you could copy one that you are comfortable with (English or Spanish, for instance) to "map_strings.it" and then edit the file to make the strings Italian (or whatever language you prefer). If you do this, please send us the file and we will add it to the distribution. You can then edit your "products.conf" and set the language extension to your new file (e.g., "it").

To make more extensive modifications to the maps you would have to edit <shakemap>/shakemap/mapping/mapmaker.py. That would require some time and a fairly extensive understanding of Python, but others have done it. We can't offer much support in that effort. Again, if you make modifications that you think would be generally useful to the ShakeMap community, please submit your modified file for our consideration.

**Comment by SergioT59** [comment]
I'm very happy to try to help you with translation, but I would to change the header of maps. In my output I have USGS, but I would inserting my network (OSB).  I have search a field containing USGS in every file in the example discharged, but I haven't found nothing.

**Comment by SergioT59** [comment]
I have modify a language file in ~/shakemap_src/shakemap/data/mapping 
inserting the italian language and then saving it as map_string.it and then have modified the products.conf data as

    language = it

and

    operator = OSB

After restart the conda system, I have try to remake an other output with an older event to seing if somewhere was change, but nothing is changed.

**Comment by cbworden** [comment]
My guess is that you modified the wrong config files. Note that the *.conf files in <shakemap>/shakemap/data should not be modified. These are the source files that are used to create your profiles. Depending upon what you did when you ran `sm_profile` your profile's config files will likely be located somewhere like `~/shakemap_profiles/default/install/config`. You can always see where your profile(s) is(are) by running `sm_profile -l`. In any event, make sure that these are the config files that you are changing.

**Comment by SergioT59** [comment]
Well, now has changed that I want and works well.
I close the issue.
When I have finished to translate, I send you a copy
