### ISSUE TITLE
export for osm

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1135]
Following the example in input of shakemap

https://earthquake.usgs.gov/earthquakes/eventpage/ci3144585

I have see a page of iteractive map that shows all in OSM map.

Is possible to know how do it?

Regards,
Sergio

**Comment by emthompson-usgs** [comment]
The web pages are not part of ShakeMap. But the folks at INGV have built a very nice interface for serving ShakeMap products:
https://github.com/INGV/shakemap4-web
I recommend trying to use their code for this purpose. You can preview what it looks like here:
http://shakemap.ingv.it/shake4/
