### ISSUE TITLE
Export legends picture

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1139]
Hi again,
is possible to extract top and bottom legends of maps as mmi_legend.png?

Regards,
Sergio

**Comment by cbworden** [comment]
Not sure exactly what you want to do, but you can do any post-processing you want using Imagemagick or Gimp or any number of other tools. If you want it to be part of the ShakeMap processing stream, you could either add it as an option at the end of mapping.py, once the images are created, or create a new coremod that runs after mapping. This would likely require some new dependencies, but you might be able to manage it with matplotlib, I'm not sure.

In any case, this is outside of anything we're likely to do. We already provide an intensity scale image that we use for the KMZ, and the header information is contained in the info.xml. You could check the info.py for ways to extract any specific information you need about the event, and process it into a png file using matplotlib.

**Comment by SergioT59** [comment]
hello Bruce,
thanks for your answer.
I'm able to output shake data in osm map reading the .json file and plots the isoline with polyline function.
To draw polylines I use color stored for every polyline. Now I whant to draw the legend for every map plotted as in following pictures

the header:

![immagine](https://user-images.githubusercontent.com/34506667/120552335-64c67c00-c3f7-11eb-814c-8ffe5f9c391e.png)

and the bottom

![immagine](https://user-images.githubusercontent.com/34506667/120552249-482a4400-c3f7-11eb-82cd-cbb1331e18d3.png)

Can I use some command to draw and save image like those?

P.S.
I haven't found file info.xml

**Comment by cbworden** [comment]
Sorry, I meant info.json, not info.xml.

I'm still not understanding what you want to do. Are you trying to create separate images of those two things that you can use elsewhere? Or are you just wanting those images at the top and bottom of the map? If so, what is the difference between what you are showing me and what is already being plotted (see image at bottom)?

If you want separate images, you have a couple of options:

1. Find the code in mapmaker.py that generates those parts of the images, copy them, and save them as JPEG, PNG or whatever.
2. Take the finished images after they are saved in mapping.py and crop out the parts you want using one of several tools available for manipulating images. Some of these will require additional dependencies to be installed in the ShakeMap virtual environment.
3. Develop your own post-processing code (or module). Again, there are a number of Python tools that will crop images. Many will require the installation of additional dependencies.

This is all getting a little bit beyond core ShakeMap functionality, so I don't think we can help you with it much more.

![psa3p0](https://user-images.githubusercontent.com/8037857/120900048-14663e80-c5f0-11eb-9855-c510eea3b947.jpg)

**Comment by SergioT59** [comment]
Thanks Bruce, 
I have solved copying the images that I needed and saved in a folder, and I show them when necessary.
Thanks for your help
Best regards,
Sergio
