### ISSUE TITLE
Map dimension

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1140]
I have noted that some plotting line goes outside the map image.
Exist a way to enlarge the images to write lines in maps?

**Comment by emthompson-usgs** [comment]
Can you provide an example map that illustrates the problem? I have not encountered this problem and I don't understand how this could happen. Are you asking about increasing the map extent in terms of lat/lon? Or the dimensions of the map image? The former is controlled by config options in `model.conf`.

**Comment by SergioT59** [comment]
Hallo Eric,
I would to extend map by lat/lon, because, when I draw poliline in OSM, someone are closed outside the map.
The example in the image show on left some wrong closure.

![immagine](https://user-images.githubusercontent.com/34506667/121040227-07914880-c7b2-11eb-8902-3b877260edfc.png)

**Comment by cbworden** [comment]
Extending the map to larger boundaries is not a problem. As Eric said, look at model.conf and you'll find various ways of doing it -- including specifying the exact bounds you want.

But keep in mind that the contour lines are absolutely NOT intended for creating polygons. They cannot and will not ever do that to your satisfaction. They don't know the difference between inside a region and outside a region. They are only intended to draw contour lines on a map and they will end at the edge of the ShakeMap mapped region. That's it. If you want to create polygons you have a variety of options (including extracting the polygons from the KMZ file), but you should read through the products section of the manual and see what works for your purposes. We make the KMZ, ESRI Raster grids, shape files, grid files, as well as JSON coverage files. But you will never, ever, get the contour files to do what you are trying to do on a consistent basis, they just aren't designed for that.

**Comment by SergioT59** [comment]
But the countour that you see I have extract fron json file from ['features']['geometry']['coordinates'] and are exactly as shakemap pictures

**Comment by SergioT59** [comment]
I have seen your kmz output. You are usine data as polyline, not as polygon like me. Now I have change it as polyline and is same as kmz output

**Comment by SergioT59** [comment]
This is my shakemap
![immagine](https://user-images.githubusercontent.com/34506667/121175095-f6e8dd00-c85a-11eb-8a1c-68055bed4125.png)

**Comment by emthompson-usgs** [comment]
The difference here is in how it is displayed. The ShakeMap that you are showing above (which I THINK is rendered using the INGV web map) is displaying the contours as lines, which is the geometric type that is appropriate for contours. As Bruce pointed out, the reason you are getting the unexpected lines crossing the map is because you were plotting them as polygons, and that is not what they are. Properly forming closed (and non-intersecting) polygons is actually very complicated and you can't just take contours and plot them as polygons. It might work in some simple cases but it will not work in general.

**Comment by cbworden** [comment]
Sergio, i was not suggesting using the *contours* from the KMZ, but there is a folder called "MMI Polygons" that contains another set of folders, each containing a set of MMI polygons at a certain MMI level. These are valid polygons. I don't know if they will plot on OSM, and they're only for MMI, but if you look at the kmz.py coremod you can see how we make them and it might be adaptable to what you want.

**Comment by SergioT59** [comment]
Hello Bruce,
i have search for folder "MMI Polygons", "MMI", "Polygons", but I haven't find it

**Comment by cbworden** [comment]
I'm not sure why it wouldn't be there. If you open the event KMZ file in google earth, you should have the option to plot the MMI polygons. To get to the data you would unzip the KMZ file (this might require changing the file extension from kmz to zip). In any event, the kml.py module demonstrates the way to make the polygons, so you should be able to make them separately if that's what you want. But my main point is that the contours won't work for making polygons.
