### ISSUE TITLE
py.test . Fails at six points

### ISSUE THREAD

**Issue by mjcrespo** [usgs/shakemap#1141]
Hello:

I have installed Shakemap in Ubuntu 20.04 LTS (virtual machine). I am trying to learn how it works.

When I run:

py.test .

it fails (i.e. there is one or two "F") at five points, namely:

multigmpe_test.py
Virtualipe_test.py
Beyer_bommer_2006_test.py
Boore_kishida_2017_test.py
Utils_test.py

and in the details given below the summary it says in all cases:

WARNING root:boore_kishida_2017.py:295 Can’t handle IMC Average horizontal, using GMAR

In any case I tried the example suggested in the wiki installation. It does the assemble (although I have to include the --force, otherwise it complains about "Out of date dependencies" and says I should run the "select" module before). Anyhow it creates the shake_data.hdf. When I try to run the "model" module it issues:

WARNING -- 2021-06-09 10:29:09 --  boore_kishida_2017._imcToFilestr -- Can’t handle IMC Average horizontal, using GMAR

So my questions are:

1. How do I solve the "F"'s during the test?
2. Do I need to run the select module? If yes, I would appreciate some guidance.

Thanks for your help.

  Maria

**Comment by emthompson-usgs** [comment]
Hi Maria, thanks for the report. 

**Regarding 1**
This may be difficult for us to help with because the pytest output can be confusing. Can you copy/past the full set of terminal output lines that have the "F" by them? There's usually a combination of dots and Fs and that helps us know exactly which test within the module fails. 

Also, the warnings you are looking at are not the reason for the failure. There should be some lines in the pytest output that that say `ERROR` rather than `WARNING`. It would help if you can find those and report them to us. 

**Regarding 2**
Generally, I think you will want to run `select`: it determines the GMPE from tectonic environment (it calls [STREC](https://github.com/usgs/strec)). It is possible to get around this if you are in a situation where you want the GMPE to be constant for all of your events.

**Comment by mjcrespo** [comment]
Hi Eric,

Thanks for your answer.

Regarding 1. Here below you have the first lines right after invoking the pytest (there are six "F"s). I have the rest of the interactive output, if you want me to paste some other lines (I do not paste it now since it would make this entry super-long).

Regarding 2. I am going to explore it further, thanks for the clarification.

Thanks for your help.


(shakemap) maria@capablanca:~/shakemap_src$ py.test .
============================= test session starts ==============================
platform linux -- Python 3.7.10, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/maria/shakemap_src, configfile: pytest.ini
plugins: cov-2.11.1, azurepipelines-0.8.0
collected 136 items                                                            

tests/shakelib/distance_test.py .....                                     [  3%]
tests/shakelib/multigmpe_test.py ............F.                           [ 13%]
tests/shakelib/sites_test.py ..                                           [ 15%]
tests/shakelib/station_test.py .....                                      [ 19%]
tests/shakelib/virtualipe_test.py F                                       [ 19%]
tests/shakelib/conversions/imc/beyer_bommer_2006_test.py F                [ 20%]
tests/shakelib/conversions/imc/boore_kishida_2017_test.py F               [ 21%]
tests/shakelib/conversions/imt/bommer_alarcon_2006_test.py .              [ 22%]
tests/shakelib/conversions/imt/newmark_hall_1982_test.py .                [ 22%]
tests/shakelib/correlation/dummy_test.py .                                [ 23%]
tests/shakelib/correlation/loth_baker_2013_test.py .                      [ 24%]
tests/shakelib/directivity/bayless2013_test.py ......                     [ 28%]
tests/shakelib/directivity/rowshandel2013_test.py .....                   [ 32%]
tests/shakelib/gmice/ak07_test.py .                                       [ 33%]
tests/shakelib/gmice/fm11_test.py .                                       [ 33%]
tests/shakelib/gmice/wald99_test.py .                                     [ 34%]
tests/shakelib/gmice/wgrw12_test.py .                                     [ 35%]
tests/shakelib/gmpe/nga_east_test.py .                                    [ 36%]
tests/shakelib/plotting/plot_rupture_test.py ..                           [ 37%]
tests/shakelib/rupture/origin_test.py .                                   [ 38%]
tests/shakelib/rupture/rupture_test.py .............                                            [ 47%]
tests/shakelib/utils/container_test.py ...                                                      [ 50%]
tests/shakelib/utils/geodetic_distance_test.py .                                                [ 50%]
tests/shakelib/utils/str_imt_test.py .                                                          [ 51%]
tests/shakelib/utils/utils_test.py ..F.F.....                                                   [ 58%]
tests/shakemap/coremods/assemble_augment_test.py ..                                             [ 60%]
tests/shakemap/coremods/assemble_sim_test.py .                                                  [ 61%]
tests/shakemap/coremods/associate_test.py .                                                     [ 61%]
tests/shakemap/coremods/contour_test.py .                                                       [ 62%]
tests/shakemap/coremods/dyfi_test.py ..                                                         [ 63%]
tests/shakemap/coremods/kml_test.py .                                                           [ 64%]
tests/shakemap/coremods/model_test.py ......                                                    [ 69%]
tests/shakemap/coremods/products_test.py ..                                                     [ 70%]
tests/shakemap/coremods/select_test.py .                                                        [ 71%]
tests/shakemap/coremods/sleep_test.py ..                                                        [ 72%]
tests/shakemap/coremods/verification_test.py ...........                                        [ 80%]
tests/shakemap/mapping/mapmaker_test.py ..                                                      [ 82%]
tests/shakemap/programs/profile_test.py .                                                       [ 83%]
tests/shakemap/programs/shake_test.py .                                                         [ 83%]
tests/shakemap/programs/sm_compare_test.py .                                                    [ 84%]
tests/shakemap/programs/sm_rupture_test.py .                                                    [ 85%]
tests/shakemap/utils/amps_test.py .                                                             [ 86%]
tests/shakemap/utils/config_test.py ..                                                          [ 87%]
tests/shakemap/utils/dependency_test.py ...                                                     [ 89%]
tests/shakemap/utils/generic_amp_test.py .                                                      [ 90%]
tests/shakemap/utils/layer_test.py .                                                            [ 91%]
tests/shakemap/utils/macros_test.py .                                                           [ 91%]
tests/shakemap/utils/probs_test.py .                                                            [ 92%]
tests/shakemap/utils/queue_test.py .....                                                        [ 96%]
tests/shakemap/utils/utilssm_test.py .....                                                      [100%]##vso[results.publish type=JUnit;runTitle='Pytest results';]/home/maria/shakemap_src/test-output.xml
##vso[task.logissue type=error;]6 test(s) failed, 136 test(s) collected.
##vso[task.logissue type=warning;]Coverage XML was not created, skipping upload.

**Comment by mjcrespo** [comment]
Hi again,

The lines where it seems to be reporting an error are copied below.

Regards,

  Maria

[...]
tests/shakelib/multigmpe_test.py:1383: AssertionError
[...]
tests/shakelib/virtualipe_test.py:188: AssertionError
[...]
shakelib/conversions/imc/beyer_bommer_2006.py:341: ValueError
[...]
tests/shakelib/conversions/imc/boore_kishida_2017_test.py:197: AssertionError
[...]
tests/shakelib/utils/utils_test.py:84: AssertionError
[...]
tests/shakelib/utils/utils_test.py:120: AssertionError
[...]
======================================= short test summary info =======================================
FAILED tests/shakelib/multigmpe_test.py::test_multigmpe_get_mean_stddevs - AssertionError: 
FAILED tests/shakelib/virtualipe_test.py::test_virtualipe - assert False
FAILED tests/shakelib/conversions/imc/beyer_bommer_2006_test.py::test_bb06 - ValueError: unknown IMC...
FAILED tests/shakelib/conversions/imc/boore_kishida_2017_test.py::test_bk17 - AssertionError: 
FAILED tests/shakelib/utils/utils_test.py::test_get_extent_small_complex - AssertionError: 
FAILED tests/shakelib/utils/utils_test.py::test_get_extent_aspect - AssertionError: 
============================= 6 failed, 130 passed in 1061.25s (0:17:41) ==============================

**Comment by cbworden** [comment]
Hi Maria,
I have been able to reproduce your errors on my system. I assume something has changed in numpy or one of or dependencies. It may take me a little while to figure it out, but this is now one of our highest priorities. I will let you know when I have a fix.
Bruce

**Comment by cbworden** [comment]
Please pull the latest code from the repo and test it. It should work now. If it does, please let us know and close this issue. Thanks for bringing it to our attention. 
Bruce

**Comment by cbworden** [comment]
Just a note of clarification: you should not need to rebuild your entire ShakeMap environment -- simply pulling from the master repository should be sufficient to fix the problem.

**Comment by mjcrespo** [comment]
Bruce,

Thank you very much. The test runs pefectly now, after following your guidance. In particular, for the thread being self content, this is what I did.

Being inside the shakemap_src directory I run:

git pull https://github.com/usgs/shakemap.git

  Maria
