### ISSUE TITLE
shakemap automatic run

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1145]
Hello,
I've make a python script to run shakemap automatically every minute, searching data in destination's folder to make a shakemap.
It works fine, but I whant change the comment when it perform the assemble.
Now it insert an old type that i have writed to try it function, and I do not how give the flag to change it.
How can I do it?

By the way, I have seen the contributors (https://earthquake.usgs.gov/data/comcat/contributor/). 
How is their contributed?

**Comment by cbworden** [comment]
When you run "assemble" you can use the '-c' flag to change the comment. For instance:

    $ shake <event_id> assemble -c "This is my comment for this event"

That same thing can be embedded in a line that does multiple commands:

    $ shake <event_id> select assemble -c "This is my comment for this event" model mapping info kml ...

If you are interested in having your network be a contributing network to the USGS, there are a number of arrangements that would need to be made. It would probably be simpler if your stations were just available via FDSN or other network connection. I am not an expert in these matters, but if you really want to pursue it, I can put you in touch with the people who maintain our seismic networks.
