### ISSUE TITLE
ValueError: numpy.ndarray size changed

### ISSUE THREAD

**Issue by raychani** [usgs/shakemap#1147]
Please describe your issue here:

I installed the 4.0.3 release by following command

`git clone -b 4.0.3 https://github.com/usgs/shakemap.git`

and following message is output when I run shake command

  File "/opt/miniconda3/envs/shakemap/bin/shake", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/opt/shakemap4/src/bin/shake", line 27, in <module>
    from shakelib.rupture.origin import read_event_file
  File "/opt/shakemap4/src/shakelib/rupture/origin.py", line 10, in <module>
    from openquake.hazardlib.geo import point
  File "/opt/miniconda3/envs/shakemap/lib/python3.7/site-packages/openquake/hazardlib/__init__.py", line 23, in <module>
    from openquake.baselib import __version__, InvalidFile
  File "/opt/miniconda3/envs/shakemap/lib/python3.7/site-packages/openquake/baselib/__init__.py", line 23, in <module>
    import pandas
  File "/opt/miniconda3/envs/shakemap/lib/python3.7/site-packages/pandas/__init__.py", line 29, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/opt/miniconda3/envs/shakemap/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

I've updated my numpy to 1.20.0 (and updated pandas to 1.2.4 automatically) like this
(the former version was 1.19)

`$ conda install numpy==1.20`

and the problem fixed.

- `python setup.py version`
running version
keywords are unexpanded, not using
got version from VCS {'version': '4.0.3', 'full-revisionid': 'cf24c8afd71bca977f96a4649fccd91c588e8d90', 'dirty': False, 'error': None, 'date': '2021-06-16T18:30:28-0600'}
Version: 4.0.3
 full-revisionid: cf24c8afd71bca977f96a4649fccd91c588e8d90
 dirty: False
 date: 2021-06-16T18:30:28-0600

- `conda --version`
conda 4.10.1
---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
Thanks for letting us know. It's hard to know all of the possible variations of the versions of the dependencies that people may have installed, so some of them may be incompatible with the latest versions of our code. When in doubt, a full reinstall should clear up any problems, but your approach may help in some cases. I'll leave this issue open for a little while so anyone searching can find it easily. But, in general, if you're having a problems like this after pulling the latest release, a full reinstall in recommended, especially if it has been a while since your last build of the ShakeMap environment.

**Comment by cbworden** [comment]
Again, as mentioned above, the fix here is to do:
```
$ conda install numpy==1.20 --force-reinstall
```
