### ISSUE TITLE
Error while reinstall shakemap.

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1149]
Hi all,
as in subject I had to reinstall shakemap, but some errors are displayed.
First off all I had receive the error of insufficient disk space, and I have deleted many files.
After that the installation is arrived at the end, but I have seen that the errors where on it.
I have try with py.test but many other error are displayed and at the end this is the result:
==================================================== short test summary info =====================================================
ERROR tests/shakelib/distance_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 8...
ERROR tests/shakelib/multigmpe_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected ...
ERROR tests/shakelib/sites_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 f...
ERROR tests/shakelib/virtualipe_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected...
ERROR tests/shakelib/conversions/imc/beyer_bommer_2006_test.py - ValueError: numpy.ndarray size changed, may indicate binary in...
ERROR tests/shakelib/conversions/imc/boore_kishida_2017_test.py - ValueError: numpy.ndarray size changed, may indicate binary i...
ERROR tests/shakelib/directivity/bayless2013_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibil...
ERROR tests/shakelib/directivity/rowshandel2013_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompati...
ERROR tests/shakelib/gmice/ak07_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected...
ERROR tests/shakelib/gmice/fm11_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected...
ERROR tests/shakelib/gmice/wald99_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expect...
ERROR tests/shakelib/gmice/wgrw12_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expect...
ERROR tests/shakelib/gmpe/nga_east_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expec...
ERROR tests/shakelib/plotting/plot_rupture_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibilit...
ERROR tests/shakelib/rupture/origin_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expe...
ERROR tests/shakelib/rupture/rupture_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Exp...
ERROR tests/shakelib/utils/container_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Exp...
ERROR tests/shakelib/utils/utils_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expecte...
ERROR tests/shakemap/coremods/assemble_augment_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatib...
ERROR tests/shakemap/coremods/assemble_sim_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibilit...
ERROR tests/shakemap/coremods/associate_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. ...
ERROR tests/shakemap/coremods/contour_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Ex...
ERROR tests/shakemap/coremods/dyfi_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expec...
ERROR tests/shakemap/coremods/kml_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expect...
ERROR tests/shakemap/coremods/model_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expe...
ERROR tests/shakemap/coremods/products_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. E...
ERROR tests/shakemap/coremods/select_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Exp...
ERROR tests/shakemap/coremods/verification_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibilit...
ERROR tests/shakemap/mapping/mapmaker_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Ex...
ERROR tests/shakemap/programs/sm_rupture_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility....
ERROR tests/shakemap/utils/amps_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected...
ERROR tests/shakemap/utils/generic_amp_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. E...
ERROR tests/shakemap/utils/layer_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expecte...
ERROR tests/shakemap/utils/probs_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expecte...
ERROR tests/shakemap/utils/queue_test.py - ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expecte...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 35 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

What can I do?
Best regards,
Sergio

**Comment by cbworden** [comment]
Hi Sergio,

As noted in issue #1147 the solution is to install numpy==1.20.

That said, a new install may be difficult right now. The Openquake people are making major changes to the hazardlib, and we are struggling to keep up. It may take another day or two before we complete our modifications and tests. And then they may change things again. If you really need something to work you may have to modify the install.sh script to tie the openquake install to an earlier tagged release. It would look something like this:
```
pip install -e git://github.com/{ username }/{ reponame }.git@{ tag name }#egg={ desired egg name }
```
I would just pick 3.11.3 since it seems to be the last tagged release before the madness started.

Good luck.

**Comment by SergioT59** [comment]
Hi Bruce,
I have seen for other error occouring during running test.py.
I have found this who is repeated many time but in different scripts:
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Also, I haven't find the pip install command with flags that you have sent me

**Comment by SergioT59** [comment]
Ok, as you suggested, I have install numpy 1.20
After that, I had running test.py, but other error where found
The error is:
E   ModuleNotFoundError: No module named 'openquake.hazardlib.gsim.atkinson_boore_2006'
and as previous post, is repeated in many test-scripts

==================================================== short test summary info =====================================================
ERROR tests/shakelib/multigmpe_test.py
ERROR tests/shakelib/utils/utils_test.py
ERROR tests/shakemap/coremods/model_test.py
ERROR tests/shakemap/coremods/products_test.py
ERROR tests/shakemap/coremods/verification_test.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by SergioT59** [comment]
Please, if another few days are needed to your team to complete modification and test, can you notify me when it is ready?
Thanks again
Sergio

**Comment by emthompson-usgs** [comment]
Bruce is working on fixing this in PR #1151. You can monitor that PR to see when the issue is resolved. Github also provides notifications of activity if you "watch" the repository (click on the "watch" button in the upper right of the repository for notification options). It is best to not rely on us for notifications.
