### ISSUE TITLE
Adding more spectral map

### ISSUE THREAD

**Issue by SergioT59** [usgs/shakemap#1154]
At first of all, thanks for the new version, I have installed without errors.
After that, as in subject, I whant make accelerations maps with other frequency. I have search in manual and in configuration files, but I haven't find on it.
How can I do?

**Comment by cbworden** [comment]
If you look in your `model.conf` file, find the section called `[interp]`. There is documentation there for `imt_list`. As an example, you could set:
```
[interp]
    imt_list = PGA, PGV, MMI, SA(0.01), SA(0.02), SA(0.03), SA(0.05), SA(0.075), SA(0.1), SA(0.15), SA(0.2), SA(0.25), SA(0.3), SA(0.4), SA(0.5), SA(0.75), SA(1.0), SA(1.5), SA(2), SA(3), SA(4), SA(5), SA(7.5)
```
That would take a little while to run, so maybe only pick one or two extra ones the first time, just to make sure it's working the way you want.

**Comment by SergioT59** [comment]
Ok, I have understands that the conf files used by program, are under shakemap_profile/default/install/config.

Thanks regards,
Sergio

**Comment by cbworden** [comment]
Yes, exactly.
