### ISSUE TITLE
ERROR collecting tests/shakelib/gmpe/nga_east_test.py

### ISSUE THREAD

**Issue by Vulum** [usgs/shakemap#1163]
Hi I am installing Shakemap via conda in Ubuntu 20.04 LTS and came up with the error below:

`ERROR collecting tests/shakelib/gmpe/nga_east_test.py _____________________________
ImportError while importing test module '/home/rimesserver02/Downloads/shakemap_src/tests/shakelib/gmpe/nga_east_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/anaconda/envs/shakemap/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/shakelib/gmpe/nga_east_test.py:12: in <module>
    from shakelib.gmpe.nga_east import NGAEast
shakelib/gmpe/nga_east.py:20: in <module>
    from openquake.hazardlib.gsim.gmpe_table import _return_tables
E   ImportError: cannot import name '_return_tables' from 'openquake.hazardlib.gsim.gmpe_table' (/opt/anaconda/envs/shakemap/lib/python3.7/site-packages/openquake/hazardlib/gsim/gmpe_table.py)
---------------- generated xml file: /home/rimesserver02/Downloads/shakemap_src/test-output.xml ----------------
=========================================== short test summary info ============================================
ERROR tests/shakelib/gmpe/nga_east_test.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 1 error in 1.53s ===============================================`

Please need some assistance.

**Comment by cbworden** [comment]
This looks like the kind of thing that happens when you haven't activated the environment before you run the tests. Did you do:
```
$ conda activate shakemap
```
after you ran `$ bash install.sh`? You need to activate the environment in the same shell where you run the tests.

**Comment by cbworden** [comment]
Reinstall ShakeMap with install.sh. If problem persists, provide more information. Closing.
