### ISSUE TITLE
missing coremods and mapping in setup.py

### ISSUE THREAD

**Issue by Mareak** [usgs/shakemap#1168]
Hi,
I manage to install shakemap with pip, everything works fine but **coremods** and **mapping** are not available.

`shakemap.coremods`, `shakemap.mapping` aren't in `setup.py` file is it on purpose ?

---

My changes:

```
setup(name='shakemap',
      version=versioneer.get_version(),
      description='USGS Near-Real-Time Ground Motion Mapping',
      author='Bruce Worden, Mike Hearne, Eric Thompson',
      author_email='cbworden@usgs.gov,mhearne@usgs.gov,emthompson@usgs.gov',
      url='http://github.com/usgs/shakemap',
      packages=[
          'shakemap',
          'shakemap.coremods',
          'shakemap.mapping',
          ...
```

Regards,

Mareak

**Comment by cbworden** [comment]
Can you explain what you are doing and why? ShakeMap is not intended to be a standalone package that is installed with pip. There is an install.sh script that should be used to create a virtual environment and install the package as described in the wiki: https://github.com/usgs/shakemap/wiki/Installation. No other approach to installing ShakeMap is supported.
