### ISSUE TITLE
Installation: 21 test fail on macOS Big Sur 11.5.2

### ISSUE THREAD

**Issue by liljas** [usgs/shakemap#1173]
Please describe your issue here:

After running install.sh without problem and activating the environment with conda activate shakemap running py.test . results in 21 failed tests:

tests/shakelib/distance_test.py .....                                    [  3%]
tests/shakelib/multigmpe_test.py ..............                          [ 13%]
tests/shakelib/sites_test.py ..                                          [ 15%]
tests/shakelib/station_test.py .....                                     [ 19%]
tests/shakelib/virtualipe_test.py .                                      [ 19%]
tests/shakelib/conversions/imc/beyer_bommer_2006_test.py .               [ 20%]
tests/shakelib/conversions/imc/boore_kishida_2017_test.py .              [ 21%]
tests/shakelib/conversions/imt/bommer_alarcon_2006_test.py .             [ 22%]
tests/shakelib/conversions/imt/newmark_hall_1982_test.py .               [ 22%]
tests/shakelib/correlation/dummy_test.py .                               [ 23%]
tests/shakelib/correlation/loth_baker_2013_test.py .                     [ 24%]
tests/shakelib/directivity/bayless2013_test.py ......                    [ 28%]
tests/shakelib/directivity/rowshandel2013_test.py .....                  [ 32%]
tests/shakelib/gmice/ak07_test.py .                                      [ 33%]
tests/shakelib/gmice/fm11_test.py .                                      [ 33%]
tests/shakelib/gmice/wald99_test.py .                                    [ 34%]
tests/shakelib/gmice/wgrw12_test.py .                                    [ 35%]
tests/shakelib/gmpe/nga_east_test.py .                                   [ 36%]
tests/shakelib/plotting/plot_rupture_test.py ..                          [ 37%]
tests/shakelib/rupture/origin_test.py .                                  [ 38%]
tests/shakelib/rupture/rupture_test.py .............                     [ 47%]
tests/shakelib/utils/container_test.py .FF                               [ 50%]
tests/shakelib/utils/geodetic_distance_test.py .                         [ 50%]
tests/shakelib/utils/str_imt_test.py .                                   [ 51%]
tests/shakelib/utils/utils_test.py ..........                            [ 58%]
tests/shakemap/coremods/assemble_augment_test.py ..                      [ 60%]
tests/shakemap/coremods/assemble_sim_test.py .                           [ 61%]
tests/shakemap/coremods/associate_test.py .                              [ 61%]
tests/shakemap/coremods/contour_test.py .                                [ 62%]
tests/shakemap/coremods/dyfi_test.py ..                                  [ 63%]
tests/shakemap/coremods/kml_test.py .                                    [ 64%]
tests/shakemap/coremods/model_test.py FFFFFF                             [ 69%]
tests/shakemap/coremods/products_test.py FF                              [ 70%]
tests/shakemap/coremods/select_test.py .                                 [ 71%]
tests/shakemap/coremods/sleep_test.py ..                                 [ 72%]
tests/shakemap/coremods/verification_test.py FFFFFFFFFFF                 [ 80%]
tests/shakemap/mapping/mapmaker_test.py ..                               [ 82%]
tests/shakemap/programs/profile_test.py .                                [ 83%]
tests/shakemap/programs/shake_test.py .                                  [ 83%]
tests/shakemap/programs/sm_compare_test.py .                             [ 84%]
tests/shakemap/programs/sm_rupture_test.py .                             [ 85%]
tests/shakemap/utils/amps_test.py .                                      [ 86%]
tests/shakemap/utils/config_test.py ..                                   [ 87%]
tests/shakemap/utils/dependency_test.py ...                              [ 89%]
tests/shakemap/utils/generic_amp_test.py .                               [ 90%]
tests/shakemap/utils/layer_test.py .                                     [ 91%]
tests/shakemap/utils/macros_test.py .                                    [ 91%]
tests/shakemap/utils/probs_test.py .                                     [ 92%]
tests/shakemap/utils/queue_test.py .....                                 [ 96%]
tests/shakemap/utils/utilssm_test.py .....                               [100%]

If you want even further information on Error messages I can provide such. 

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
Yeah, we're going to need to see the details. We routinely test on MacOS 10.15, so something isn't right. We have been tracking some errors with the Natural Earth server, so if those seem to be the errors you're seeing, you may just have to wait for a fix. Otherwise we'll need details.

**Comment by liljas** [comment]
[test-output.xlsx](https://github.com/usgs/shakemap/files/7198270/test-output.xlsx)

Here is the test output, as from the running at least for now.

**Comment by cbworden** [comment]
The errors you are getting indicate that your ShakeMap code revision is behind your impactutils code. It looks to me like you've updated your environment (impactutils in particular), but have not updated the actual ShakeMap code to the latest revision. Make sure to checkout v4.0.5, or v4.1.0-beta.2, or even the master from the ShakeMap repo (depending upon your preference).

**Comment by liljas** [comment]
Thank you. Switching to c4.0.5 worked perfectly.
