### ISSUE TITLE
Possible missing step in documentation example

### ISSUE THREAD

**Issue by gmfricke** [usgs/shakemap#1174]
https://github.com/usgs/shakemap/wiki/inputs page of the example seems to be missing "shake ci3144585 select" which causes "shake ci3144585 assemble" to throw an out of date dependencies error.

**Comment by cbworden** [comment]
Thanks for the heads up. It's been a while since we've gone through those instructions in detail. I've edited the wiki to add the additional step of running `select` before running `assemble`. 

Let us know if you find any other issues with the docs.
