### ISSUE TITLE
M5.8 Vanuatu event has lon/lat span close to 20 degrees

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#1207]
Please describe your issue here:
This event: 
https://earthquake.usgs.gov/earthquakes/eventpage/us7000fx5p/shakemap/intensity

has a very large extent for a magnitude of 5.8, and has an MMI of 1 at the edges.

**Comment by emthompson-usgs** [comment]
The extent is the least of the problems with this shakemap.

**Comment by emthompson-usgs** [comment]
PGV of -2.7 cm/s?

**Comment by emthompson-usgs** [comment]
PGA and all SA are exactly zero?

**Comment by emthompson-usgs** [comment]
After troubleshooting to get shakemap to get through mapping on my machine, I get wildly different results than what is in comcat:
![intensity_us7000fx5p_local](https://user-images.githubusercontent.com/15928870/152008031-2afbcbe7-a89a-40b4-9e9f-47852f73c42b.jpg)
compare to what is on comcat:
![intensity_us7000fx5p_comcat](https://user-images.githubusercontent.com/15928870/152008054-f0f1fef3-ea55-4c13-b3ce-826d76cf4a1d.jpeg)

**Comment by emthompson-usgs** [comment]
To be clear, I'm not suggesting that the larger MMI values that I'm getting make any sense. But if it is impossible to reproduce what is going on with the production install of shakemap, I can't debug the extent issue.

**Comment by cbworden** [comment]
Closed by #1211
