### ISSUE TITLE
BSSC2014 scenario rupture.json is an unknown format

### ISSUE THREAD

**Issue by PSGreene** [usgs/shakemap#1219]
When I try to run earthquake scenarios from the bssc2014 catalog the assemble function fails and returns these messages: 
```
(shakemap) masszeop@R:~$ shake bssc2014sanandreascoachellar_m7p11_se assemble
INFO -- 2022-05-04 09:16:17 -- shake.main -- Running command assemble
Please enter a comment for this version.
comment: test
WARNING -- 2022-05-04 09:16:20 -- factory.get_rupture -- Unknown exception reading fault file: Json metadata field should contain "reference" key.
ERROR -- 2022-05-04 09:16:20 -- factory.get_rupture -- 'Rupture file /home/masszeop/shakemap_profiles/default/data/bssc2014sanandreascoachellar_m7p11_se/current/rupture.json is not in lat, lon, depth format.'
CRITICAL -- 2022-05-04 09:16:20 -- shake.main --
Earthquake: M7.1 San Andreas (Coachella) rev
Host: R
Event ID: bssc2014sanandreascoachellar_m7p11_se
Exception: Unknown rupture file format.
Stack Trace:   File "/home/masszeop/shakemap_src/bin/shake", line 348, in main
    obj.execute()
  File "/home/masszeop/shakemap_src/shakemap/coremods/assemble.py", line 247, in execute
    shake_data = ShakeMapInputContainer.createFromInput(
  File "/home/masszeop/shakemap_src/shakelib/utils/containers.py", line 72, in createFromInput
    rupture = get_rupture(origin, file=rupturefile)
  File "/home/masszeop/shakemap_src/shakelib/rupture/factory.py", line 92, in get_rupture
    raise IOError("Unknown rupture file format.")
```
I don't know if this is an issue for all earthquakes in the bssc2014 catalog but I have yet to find one that works.

Before diving into reformatting the rupture files, I figured I should check in to see if there is a way to have shakemap read the current format. 

Thanks!

Phil

**Comment by cbworden** [comment]
Let us think about our support for scenarios and get back to you. Some of them are definitely archival -- that means that the inputs and products will never change. There are others that we might keep updated. I think we have to decide how much we want to invest in maintaining legacy products as our systems move forward. We certainly haven't considered users rerunning scenarios and I can't encourage you that it is something that we're going to support.

**Comment by emthompson-usgs** [comment]
@PSGreene I just got back from a week of vacation and I will respond to this as soon as I can. 

@cbworden I have been communicating with @PSGreene and this is a somewhat unique need/request. I think I can support it in this case. I think he posted here because I haven't been responsive to email because I've been away.

**Comment by emthompson-usgs** [comment]
The issue was that the BSSC event ruptures didn't have a "reference" in the metadata. The solution is to add this to the JSON file.
