### ISSUE TITLE
RASTERIO - topografy error in Release 4.1.1

### ISSUE THREAD

**Issue by LiciaFaenza** [usgs/shakemap#1220]
Dear Bruce, Dear All,
We have installed the new version of shakemap, the release 4.1.1.
The installation was successful, but we saw that the maps did not have topography when we started running the code.
Going into the details of the “warnings” that the code produces, we noticed a new one compared to those in previous versions:
```
WARNING -- 2022-05-04 10:09:30 -- warnings._showwarnmsg -- /home/shake/miniconda/envs/shakemap/lib/python3.8/site-packages/rasterio/__init__.py:220: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
```
Trying to understand the detail better, we realise that the problem is in the version of RASTERIO. The previous release of ShakeMap had version 1.2.5 of RASTERIO, and it can read the file topo_30sec.grd. The new version of ShakeMap has instead installed version 1.2.10. of RASTERIO, and when I try to read the file topo_30sec.grd I get the same WARNING message that I have with ShakeMap.
We tried to force the code “install.sh” with the version RASTERIO 1.2.5, but the compilation failed due to conflicts.
Do you have any idea how to fix this problem? Are there any changes to the topo_30sec.grd file so that the new version of RASTERIO can read it?
I really appreciate any help you can provide.

---
We have:

```
(shakemap) shake@503f39036473:~/gitwork/shakemap_src$ python setup.py -V
0.0.0
(shakemap) shake@503f39036473:~/gitwork/shakemap_src$ uname -v 
#1 SMP Debian 4.9.272-2 (2021-07-19)
(shakemap) shake@503f39036473:~/gitwork/shakemap_src$ conda --version
conda 4.12.0

```

Thank you
Licia

**Comment by cbworden** [comment]
Hi Licia,

Yes, this is an issue. You should be able to solve it, however. Activate your shakemap environment, then locate your topography .grd file. (If in doubt look in ~/shakemap_profiles/<profile>/install/config/products.conf). Then run the program "fix_netcdf  <topo_file.grd>". This should report whether it did something or not. If it did, then your topography should start working again.

You will likely still see a lot of warning messages when you run the mapping module. We don't control those, and hopefully they will go away when the cartopy people update their codes.

Bruce

**Comment by LiciaFaenza** [comment]
Dear Bruce, 

Thank you for the quick reply. I was able to solve the problem with "fix_netcdf".  It made the following change to the topography file:

```
(shakemap) shake@36c270c983e8:~/shakemap_data/topo$ fix_netcdf topo_30sec.grd 
File topo_30sec.grd now has 'axis' attributes on 'x' and 'y' variables
```


ciao
Licia
