### ISSUE TITLE
shakelib missing 'rupture' module, used by shakemap-aqms: aqms_db2xml.py

### ISSUE THREAD

**Issue by millpaul** [usgs/shakemap#1229]
The former version 4.0 of shakemap had a sub-dir named 'rupture' under dir 'shakelib', but the new 4.1 version lacks this.
As a result, when I run shake with aqms integrated, the shakemap_aqms/coremods/aqms_db2xml.py tries to load the rupture module, specifically to import the Origin function, but fails.

here is the command line:

(shakemap) [ncss@ucbrt-test default]$ shake -h
Traceback (most recent call last):
  File "/home/ncss/miniconda/envs/shakemap/bin/shake", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ncss/software/ShakeMap4/shakemap_src/bin/shake", line 89, in <module>
    _classes_ = _get_command_classes(_config_)
  File "/home/ncss/software/ShakeMap4/shakemap_src/bin/shake", line 56, in _get_command_classes
    cm = {
  File "/home/ncss/software/ShakeMap4/shakemap_src/bin/shake", line 57, in <dictcomp>
    name: importlib.import_module(name)
  File "/home/ncss/miniconda/envs/shakemap/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ncss/miniconda/envs/shakemap/lib/python3.8/site-packages/shakemap_aqms/coremods/aqms_db2xml.py", line 14, in <module>
    from shakelib.rupture.origin import Origin
ModuleNotFoundError: No module named 'shakelib.rupture'

Paul.
email: millpaul@seismo.berkeley.edu

**Comment by emthompson-usgs** [comment]
Hi @millpaul, we moved that package to it's own repository here: 
https://code.usgs.gov/ghsc/esi/esi-utils-rupture
The reason is that there are aspects of this package that are useful for other situations and we didn't want to have to require full installation of shakemap just to be able to use some of these rupture and distance functions. The internal structure of the package hasn't changed, though, so changing the imports to match should be simple and easy. For example
```
from shakelib.rupture.origin import Origin
```
will become
```
from esi_utils_rupture.origin import Origin
```
And the `esi-utils-rupture` package is easy to install via
```
pip install esi-utils-rupture
```

**Comment by cbworden** [comment]
Hi @millpaul, @emthompson-usgs is correct that this is the current way to do it now, but you are using the latest ShakeMap installation that hasn't been fully converted to use the new "esi-" packages yet. So at this point you should use the rupture package built into impactutils, which is installed into your shakemap environment by default:

`from impactutils.rupture.origin import Origin`

Once ShakeMap is converted to use the esi- packages, you'll want to change shakemap-aqms *again* to use the import line that @emthompson-usgs recommends.

**Comment by millpaul** [comment]
Hi Bruce,
well, it did work!

I modified both files: aqms_db2xml.py & aqms_eq2xml.py
to import 'Origin' & 'write_event_file' from impactutils.rupture.origin

and I now get shake to run:

(shakemap) ***@***.*** coremods]$ shake -v
ShakeMap version v4.1.2+4.g5ef0764.dirty

Paul.

--------------
Paul Milligan
Geophysicist & Software Engineer
Berkeley Seismological Lab

Paul Milligan wrote:

**Comment by millpaul** [comment]
Bruce Worden's solution worked best:

modify the shakemap-aqms .py files that call for import Origin,
aqms_db2xml.py orig: 
       from shakelib.rupture.origin import Origin
new:
      from impactutils.rupture.origin import Origin

aqms_eq2xml.py orig:
      from shakelib.rupture.origin import write_event_file
new: 
   from impactutils.rupture.origin import write_event_file

Paul.

**Comment by cbworden** [comment]
Thanks @millpaul, I'm glad it worked. Remember that @emthompson-usgs solution will be needed soon (except we will do the pip install part as part of the ShakeMap install).

Li Zhang, can you and Ellen make sure that you have full access to this repo, and make and commit these changes? It might even be worth tagging a release. Then you can do another release when we do the "esi-" updates to ShakeMap (and you do the similar updates to this package).

**Comment by millpaul** [comment]
Bruce,
where is the shakemap-aqms repo ?
I looked for it under github.com/usgs/, but could not find it.

I'm currently using Garry Gann's old shakemap-aqms code tree.

Paul.


--------------
Paul Milligan
Geophysicist & Software Engineer
Berkeley Seismological Lab

C. Bruce Worden wrote:

**Comment by cbworden** [comment]
Oh, ha, I thought we were in it. It's https://github.com/shakemap-ci/shakemap-aqms

**Comment by cbworden** [comment]
This is actually https://github.com/shakemap-ci/shakemap-aqms/issues/4

**Comment by cbworden** [comment]
Closing here. Further discussion can happen on https://github.com/shakemap-ci/shakemap-aqms/issues/4.

**Comment by millpaul** [comment]
Ok Bruce,
thanks for location of the shakemap-aqms repo under 
github.com/shakemap-ci/shakemap-aqms
Paul.

--------------
Paul Milligan
Geophysicist & Software Engineer
Berkeley Seismological Lab

C. Bruce Worden wrote:

**Comment by dutchTender** [comment]
@cbworden i have a fork of the https://github.com/shakemap-ci/shakemap-aqms/, i can make the update to my fork and submit a pull request. would that be sufficient?

**Comment by cbworden** [comment]
@dutchTender, that's great. You are the owners of that repo, not me, so you'll want to merge your own PRs and create tags as you see fit. Just let me know as problems arise.

**Comment by dutchTender** [comment]
got it Bruce. i will have ellen add me as a maintainer. i don't think i am
right now.

**Comment by millpaul** [comment]
Bruce,
I don't think this will work, as I can't find any code module, or .py file 
or dir named 'impactutils' anywhere under the USGS github shakemap tree.

Paul.

--------------
Paul Milligan
Geophysicist & Software Engineer
Berkeley Seismological Lab

C. Bruce Worden wrote:

**Comment by emthompson-usgs** [comment]
impactutils is an external dependency: 
https://github.com/usgs/shakemap/blob/main/source_environment.yml#L18
https://github.com/usgs/earthquake-impact-utils/tree/main/impactutils
