### ISSUE TITLE
intensity_flag not taken into account

### ISSUE THREAD

**Issue by lpellorce** [usgs/shakemap#1249]
Hi,

I have a problem when trying to manually flag a macroseismic intensity data. Following the guideline of the manual, I set an `intensity_flag="M"` but it is not taken into account. While looking into the `stationlist.json` output file, I see `intensity_flag="0"` for all macroseismic intensities, no matter what I set in the input data file.
 
My input `macro_dat.xml` file : 

     <stationlist created="1640995202" nbresp="3">
     <station code="32905" name="BORON (Intensity 5, 1 responses)" insttype="BCSF" lat="47.56000" lon="7.01000" source="BCSF (EMS98)" netid="INTENSITY" commtype="DIG" intensity="5" intensity_stddev="0.3" intensity_flag="M">
     </station>
     <station code="32983" name="TREVENANS (Intensity 5, 2 responses)" insttype="BCSF" lat="47.57000" lon="6.86000" source="BCSF (EMS98)" netid="INTENSITY" commtype="DIG" intensity="5" intensity_stddev="0.3" intensity_flag="0">
     </station>
     </stationlist>

Thanks in advance for your help.

**Comment by cbworden** [comment]
I've put in a fix for this issue.

You will want to do a pull on the repo. Depending on when you last did a pull and installed, you may or may not have to re-install ShakeMap. This fix should not require a reinstall, but when you pull (depending on when you last did a pull) you may get other changes that do require a reinstall.

Either way, let us know if the fix works for you.

**Comment by lpellorce** [comment]
That works perfectly, thank you.

**Comment by cbworden** [comment]
Thanks for the bug report.
