### ISSUE TITLE
Troubleshooting Fault Rupture Events in ShakeMap: An Issue with Faults.json File

### ISSUE THREAD

**Issue by mrdimentio** [usgs/shakemap#1257]
Help! I've recently installed ShakeMap and have successfully processed a number of events. However, when I tried to simulate events with fault rupture, I encountered persistent issues with my faults.json file, despite numerous edits.

In my case, I selected a fault polygon (for the sake of simplicity, let's assume a square) and translated it into a multipolygon geojson file. Unfortunately, this hasn't worked. Is there something I'm missing? I would appreciate any guidance on this matter.

**Comment by emthompson-usgs** [comment]
@mrdimentio, thanks for contacting us. Note that this repository has been moved to:
https://github.com/DOI-USGS/ghsc-esi-shakemap
Please send future issues there, and be sure that you are installing that latest version from there. 

Also, we will need more details to be able to identify the issue with your rupture file. Note that we do apply additional constraints to the polygon beyond that of a geojson multipolygon. So I a valid multipolygon is not necessarily a valid rupture. For details, see here:
https://cbworden.github.io/shakemap/manual4_0/sg_input_formats.html#rupture-specification

If you still have problems after reading that, please let us know what error messages you are getting in the shakemap log.

**Comment by emthompson-usgs** [comment]
I suspect that the issue is that all of the points are at the same depth, and so there is no "top edge" vs "bottom edge" of the fault plane. I suggest giving the bottom edge a non-zero depth to see if this fixes the issue (see below). This should make it a valid rupture polygon, but it may not be what you want. 
```json
      "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                -118.6914141825694,
                34.263262137192335,
                0
              ],
              [
                -118.58600731599527,
                34.40023751028014,
                0
              ],
              [
                -118.42013449495222,
                34.31389485020226,
                1.0
              ],
              [
                -118.52554136152635,
                34.17610253955423,
                1.0
              ],
              [
                -118.6914141825694,
                34.263262137192335,
                0
              ]
            ]
          ]
        ]
      }

```

**Comment by mrdimentio** [comment]
hank you very much, the rupture.json file has now worked correctly. ;)
