### ISSUE TITLE
Create Jenkins testing system

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#224]
This is for system testing and automatic documentation generation.

**Comment by emthompson-usgs** [comment]
I think it is time to prioritize this. Also, I don't think we need to for documentation, but more like system tests where it might have a list of global events that it loops over and runs.

**Comment by mhearne-usgs** [comment]
us2000a9n1 - 180 meridian
us2000cymg - high latitude
us20005j32 - equator
us2000ajpe - all ocean (also spans prime meridian)
