### ISSUE TITLE
Have a discussion about event-specific configs and run history

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#277]
We have vaguely discussed the notion of having a system-wide
config (or set of configs, a la ShakeMap 3.5 and earlier) for
ShakeMap v4.  The details of this config file format have yet to
be fully fleshed out (although the configobj module has been
tested).  This issue describes a discussion about how to capture
event-specific configs, and event run history.

Some definitions: 

1) System config - one system-wide config
file (or set of files) that set defaults for all runs of the
software.  This could include things like the default resolution
of the map in X and Y, or the colors for road networks on maps,
etc.  _Some_ of these parameters can also be set on the command
line.  Any command line parameter for any program can be also set in 
a config file, but not every config parameter can be set on the command line.

2) Event config - a single file (probably) in the event directory
that contains options that should override the options found in
the system config.  As above, this file could contain command
line parameters as well as more complex options that cannot be
set on the command line.

3) Event history - A file or database (probably SQLITE, in that
case) that lives in the event directory and keeps track of what
command line flags were used for each program at any given time.
This file could look something like this:

2016-10-11T20:37:23.123 grind -event 20111023104121 -psa -qtm -lonspan 4.3 -lonoff 2.1
2016-10-11T20:37:24.678 mapping -event 20111023104121 -timestamp -notchecked -itopo -verbose -gsm

There is some debate as to whether we need all of these files,
or if the event config should have command line options in it.

A discussion of this should include users who are not developers.

**Comment by mhearne-usgs** [comment]
Addendum:  @wald-usgs pointed out that we could do away with command line options completely, and just have a system-wide config and an optional event-specific config.  Upon further discussion, we added to this notion an event history which would look something like this:

us2016abcd/ (top level event folder)
                    /config/params.conf (only those options to override the system defaults)
                    /.log/20161012T123456_123.grind.conf
                   /.log/20161012T123458_123.transfer.conf

These timestamped .conf files are a copy of whatever the params.conf file looked like at the time that command (grind, transfer, etc.) was run.

**Comment by emthompson-usgs** [comment]
I believe that this is now resolved with the use of configobj so I'm closing.
