### ISSUE TITLE
Handle time zones, possibly including "local" time.

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#303]
My proposal is that we allow time zone strings in event.xml to be one of:
1) UTC
2) Any of the Olsen time zone names: Africa/Abidjan, etc.
3) the string "local"

If set to "local", then ShakeMap should:
1) Using the given time, latitude and longitude, figure out what time zone the event is in.
2) Output that time on maps and in data files in the Olsen representation of that time zone.

If set to UTC or any of the Olsen time zones, defer to the timezone set in the global or event-specific config file.

More debate is presumed to follow.

**Comment by jmfee-usgs** [comment]
I suggest you _always_ include an absolute UTC reference time, and then allow additional "local"/non-UTC times when desired.

**Comment by mhearne-usgs** [comment]
Just implement this on maps, and think about scenario problem (specifying time for scenarios in local time zone, somehow not in event.xml)
