### ISSUE TITLE
Refactor programs

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#355]
Create "shake" meta-program and move command line programs to "plugin" modules, in a directory called "coremods".

**Comment by emthompson-usgs** [comment]
Assigned to Bruce because he's already working on it. I added myself because can help if you can let me know what part of this I can work on without creating merge conflicts.

**Comment by cbworden** [comment]
Mostly done. Needs cleanup and testing. Splitting this ticket into smaller issues.
