### ISSUE TITLE
Prototype select method

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#375]
- Create example STREC output files for different conditions, including distances and slab info for subduction zones.
- Create initial/prototype version of select "coremod".

**Comment by cbworden** [comment]
Select module exists. We need the get_tectonic_region() function (layers.py) to query strec and build the returned dictionary (including probabilities). The existing get_tectonic_region() is just a placeholder.

**Comment by mhearne-usgs** [comment]
Issues to consider:
 - What should depth uncertainty be (from STREC) when event occurs inside subduction zone but is not inside a slab? (Currently NaN)
 - What should STREC return, and what will select do, when two slabs overlap?
 - Should STREC try to find a composite moment tensor for an event that does not have a computed one?

**Comment by emthompson-usgs** [comment]
Although this was assigned to me, I believe that it is now closed by @mhearne-usgs with PR #428.
