### ISSUE TITLE
Implement automated versioning (with manual tags)

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#38]
For the pyshake package, modify the __init__.py script to include something like:

__version__ = 'version'

Then create a pre-commit hook script that looks like this:

#!/bin/sh

version=`git describe --long | awk -F- '{print $1"."$2}'`

cd pyshake
sed -i.bak "s/'.*'/'${version}'/g" __init__.py
rm *.bak

For this to work, we would need to create one annotated tag (say 4.0) using the "git tag"  command.  The pyshake version number would then be 4.0.N, where N is the number of commits since the 4.0 tag was created.

**Comment by mhearne-usgs** [comment]
The problem with the above approach is that you're left with a changed __init__.py file *after* each commit.  Instead of a pre-commit hook, we may have to have a "setversion" script that we run instead.

**Comment by emthompson-usgs** [comment]
Using versioneer along with creating releases on the upstream repository to increment the version number seems to work. As a matter of habit, we should add '--tags' to our pull requests to ensure that everyone contributing is up to date with the release tag.
