### ISSUE TITLE
Clean up files after tests

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#385]
test_assemble.py and probably other test scripts leave HDF files hanging around after the tests are run for the first time.  Generally speaking, this is a bad idea.  Additionally, for test_assemble this has the added effect that if the test is run for a second time, different branches of the assemble module code are exercised.  This is also a bad idea.

**Comment by cbworden** [comment]
Fixed. Tests clean up after themselves much better now.
