### ISSUE TITLE
Map fix it

### ISSUE THREAD

**Issue by cbworden** [usgs/shakemap#391]
Add things here:
x City names on top of ocean -- done (CBW)
o MMI coloring of station should use MMI from IMT of plot 
x Triangles for seismic stations -- done (CBW)
o Optionally remove topography and cities
o Dashed contours over ocean
o Render fault outline on map

**Comment by emthompson-usgs** [comment]
I think all these are done except for option to remove topo and cities.

**Comment by cbworden** [comment]
We're going to rewrite the mapping module.
