### ISSUE TITLE
Need more GMICE

### ISSUE THREAD

**Issue by cbworden** [usgs/shakemap#415]
[x] Wald et al 1999
[?] Atkinson & Kaka 2007
[ ] Faenza & Michelini
???

**Comment by mhearne-usgs** [comment]
Also re-factor existing classes to use a common parent class.

**Comment by vinceq-usgs** [comment]
Almost finished coding this, should I just send a pull request?

**Comment by cbworden** [comment]
Yes, that will work. Note that there was also an F&M paper in 2011 that added PSA to the conversions. Are you including that, as well?

**Comment by vinceq-usgs** [comment]
No, I didn't see that... do you have a link to it?

- Vince

--
Vince Quitoriano (vinceq@usgs.gov) - USGS Contractor
USGS Did You Feel It?    http://earthquake.usgs.gov/earthquakes/dyfi
USGS ShakeMaps:        http://earthquake.usgs.gov/earthquakes/shakemap

**Comment by cbworden** [comment]
Here’s the paper.

**Comment by cbworden** [comment]
Waiting to resolve standard deviation issue.
