### ISSUE TITLE
Create ShakeMap triggering/amp processing scripts

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#426]
Two big programs should be written:
 - process_amps, which:
   - looks at a polling directory for unassociated amplitudes
   - looks at a sqlite database (created by process_origins) for event info
   - associates amps with events
   - writes data files in appropriate directories
   - (potentially) sets a flag in event table saying event has been updated
   - (potentially) runs shake.
 - process_origins, which:
   - is either called via command line (w/ PDL arguments) OR via a socket, with input arguments of id, time, lat, lon, depth, magnitude, and run/cancel flag.
   - filters out events not inside configured regions, or too small, or ??
   - runs shake on origins passed.
   - adds event to a sqlite database.
   - (potentially) looks at events which have been flagged by process_amps and runs those as well.

Potential issues: sqlite locking (possible simultaneous reads/writes ok?)

Other scripts:

 - python version of get_dyfi

For AQMS environments:
 - a runshake script that gets called from a stored procedure and calls process_origins via socket.
 - eq2xml or python equivalent
 - db2xml or python equivalent

For PDL environments:
 - A dump_amps script which gets called by PDL

**Comment by cbworden** [comment]
This is all pretty much handled by process_amps, process_origins, sm_queue, and the AQMS repo.
