### ISSUE TITLE
Outdated notebooks

### ISSUE THREAD

**Issue by Yajing-Zhao** [usgs/shakemap#430]
Hi, thank you for making shakemap available on Github!

I just installed it and wanted to run the notebooks as a starting point, but I realized both of them are outdated. For example 'import shakemap.grind.fault as fault' in "Read and display UCERF3 Fault.ipynb" gives me error. 

Can you update those two files to reflect the current version of shakemap, or what starting point do you recommend for the starter to become familiar with the code?

**Comment by emthompson-usgs** [comment]
Hi Yajing - Thanks for letting us know. I will fix this since I think I was the one who made that notebook. We don't currently have a method for ensuring that notebooks get updated when the code changes.

**Comment by emthompson-usgs** [comment]
@Yajing-Zhao After discussing this with the other developers, we realized that the notebooks may not be what you want. I have updated them in a PR that will close this issue (please see the readme I added to the notebooks directory). You may find the wiki that we just created more useful.
