### ISSUE TITLE
sm_profile

### ISSUE THREAD

**Issue by cbworden** [usgs/shakemap#436]
2 issues:
1) Consistency check on startup: do the listed profile directories exist? If not, delete the profile.
2) When the user deletes a profile, add a message that to complete the deletion, they need to remove the associated profile directory (after saving anything important).

**Comment by emthompson-usgs** [comment]
Additional note: it is not save to automatically delete the parent directory because the user could have manually set the path so that it contains data that is not intended to be deleted.
