### ISSUE TITLE
Consistent amplitudes formatting (stationlist.json)

### ISSUE THREAD

**Issue by dslosky-usgs** [usgs/shakemap#457]
The current stationlist.json formatting can be found here:
http://usgs.github.io/shakemap/manual4_0/tg_formats.html#stationlist-geojson

The amplitudes array (`<feature>["properties"]["channels"][<channel>]["amplitudes"]`) could be modified to use the same format as the "predictions" (`<feature>["predictions"]`) and "mmi_from_pgm" (`<feature>["mmi_from_pgm"]`) objects.

**Current formatting:**

```
"amplitudes": [
          {
            "value": 0.0063,
            "units": "%g",
            "name": "sa(3.0)",
            "ln_sigma": 0,
            "flag": "0"
          },
          {
            "value": 0.0094,
            "units": "cm/s",
            "name": "pgv",
            "ln_sigma": 0,
            "flag": "0"
          },
          ...
        ]
```

**Suggested formatting:**

```
"amplitudes": {
          "sa(3.0)": {
            "value": 0.0063,
            "units": "%g",
            "ln_sigma": 0,
            "flag": "0"
          },
          "pgv": {
            "value": 0.0094,
            "units": "cm/s",
            "ln_sigma": 0,
            "flag": "0"
          },
          ...
        }
```

The current formatting leads to an XML-like parse where every array item must be iterated over until a specific `"name"` is found.  The suggested formatting will be easier to render in the web and is more consistent with the other formatting in stationlist.json. However, the current formatting can still be presented in the web with some manipulation.

**Comment by jmfee-usgs** [comment]
@dslosky-usgs it is considered a best practice to not include values in object keys:
    https://github.com/WhiteHouse/api-standards#responses

I recommend iterating over the array of objects to build an index based on name before rendering:
```javascript
const amplitudeIndex = {};
amplitudes.forEach((amplitude) => {
  amplitudeIndex[amplitude.name] = amplitude;
});

// render as usual
```

If you still want to change the data format, at least keep the name as part of the objects.

**Comment by cbworden** [comment]
Currently the new stationlist is a mix of these two structures. If the list (vs. the “dictionary”) approach is preferred, then I should probably revise the code to make the “predictions", “mmi_from_pgm", and “pgm_from_mmi” structures into list-like structures with the current keys refactored to be the value associated with a “name” key.

Daniel, can you work with that?

Bruce

**Comment by dslosky-usgs** [comment]
@jmfee-usgs Thanks for that link, I hadn't seen it before! There's actually a lot of useful stuff in there... 

@cbworden absolutely! I think consistency is key here and I'm all for following the best practices.

**Comment by cbworden** [comment]
Stationlist was revised to use list-like structures rather than dictionary-like structures.
