### ISSUE TITLE
from intensity map to contours

### ISSUE THREAD

**Issue by Yajing-Zhao** [usgs/shakemap#479]
Hi, I am a newbie. 
I am not sure if I can generate contours if I have the intensity map using this software.
I will really appreciate it if you can give me any ideas or advice?

**Comment by emthompson-usgs** [comment]
Hi Yajing, 

Did you create the intensity map with the code in this repository? If so, then you should also be able to generate a contour map and also contour files. I think the [mapping](https://github.com/usgs/shakemap/wiki/mapping) and [contour](https://github.com/usgs/shakemap/wiki/contours) sections of the wiki will be helpful for you. 

Eric

**Comment by Yajing-Zhao** [comment]
Thanks for your advice but I didn't create the intensity map with the code in this repository. I mean someone can only supply the intensity map to me and I am not sure if I can generate the contour map from the intensity map using the code in this repository. Thanks a lot for your patience.

**Comment by emthompson-usgs** [comment]
No, we do not have methods for creating contours from intensity maps.
