### ISSUE TITLE
Moment tensors in select.py

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#493]
In select.py
tensor_params = org.moment.copy()
doesn't appear to every get tested. When I tried to write a test it doesn't work. I think that this means that the moment tensor information is never getting used by select.

**Comment by mhearne-usgs** [comment]
We need to implement something that allows select to take in a moment tensor (something embedded in shake_data, or a file in the data directory?) instead of depending on ComCat.

**Comment by nackerley** [comment]
We will be needing this feature here at the Canadian Hazards Information Service. Given that the project already has an obspy dependency, the obvious thing seems to me to be to allow specification of all event parameters by supplying a QuakeML file.
