### ISSUE TITLE
Choose SM35 => SM40 GMPE translations

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#519]
Go through migrate.conf and find openquake equivalents for all SM35 GMPEs.

**Comment by emthompson-usgs** [comment]
Small semantic issue, for documentation etc.: I think we should avoid the term "equivalents" because there won't always be an equivalent but we will need a reasonable option that is available in OQ. Perhaps the term "substitution" or "alternative" is better.
