### ISSUE TITLE
info.json

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#520]
- Bias entires include array/list brackets
- Add more granularity of information on GMPE set (yes Mike, this was what you wanted originally and I didn't like it but you were right)

**Comment by cbworden** [comment]
I fixed the bias thing, but not sure what we want for the GMPE set. It's complicated since the multigmpe is IMT, site, and distance specific. And the multigmpe can be made of gmpe sets, so do we want to list each set and its constituents, or just the final list of gmpes and their total weights?

**Comment by mhearne-usgs** [comment]
Make a more detailed json structure with all multigmpe details, probably not rendered in metadata tab.
