### ISSUE TITLE
Write a makefault program to allow users to create rupture files without editing by hand

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#532]
We have all sorts of constructors for rupture objects, we might as well use them:
 - specify top vertices, width and dip
 - ??

**Comment by wald-usgs** [comment]
More often than not, scenario fault geometry is supplied by four or more vertices (top and bottom of fault) rather than top/dip/width.

**Comment by mhearne-usgs** [comment]
Agreed. The point here is that we have methods implemented in code that allow faults to be constructed in many ways, which then turn input data into a fully specified rupture file which contains either a sequence of quadrilaterals or one multi-vertex polygon.  At least in the first case, you can specify a quadrilateral by either providing all of the vertices, or specifying the top two vertices, a width, and a dip, which will then be transformed into all four vertices via clever trigonometry.  We could imagine other ways the fault could be constructed without having to specify every vertex.

**Comment by cbworden** [comment]
Attn: @dslosky-usgs
