### ISSUE TITLE
What is our standard for geojson format rupture file names?

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#537]
Currently this is encoded in assemble.py, sm_create, and sm_migrate as *_fault.geojson.

If we want to change this to something else we'll need to do it in those three places.

Decision: Modify assemble to look for rupture.json, and sm_migrate and sm_create to create rupture.json.

**Comment by emthompson-usgs** [comment]
My preference is to call it "rupture.json" and maybe allow a prefix to be appended.

**Comment by mhearne-usgs** [comment]
This has now been burned into the code  - assemble/augment now look for this, and sm_migrate and sm_create write it.
