### ISSUE TITLE
Implement new class method for QuadRupture

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#549]
Many papers describe faults with a point on the plane, and then other relevant information about rupture dimensions. See attached diagram.

**Comment by mhearne-usgs** [comment]
![img_1480](https://user-images.githubusercontent.com/303058/39899627-4b4bfb78-547a-11e8-95da-f2776bb66537.jpg)

**Comment by emthompson-usgs** [comment]
Also, remember to allow for multiple planes.
