### ISSUE TITLE
grid.xml: urat and svel

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#552]
Shakemap 3.5 has `urat` and `svel` columns and we did not include them in Shakemap 4.0 grids. Should we include them for backwards compatibility? It came up because the ground-failure product makes use `urat` and so it won't work as-is with Shakemap 4.0 grids. I'm not sure if it is better to support these legacy columns or to change ground-failure to do something smarter with Shakemap 4.0 (e.g., use the `shake_result.hdf` file).

**Comment by cbworden** [comment]
urat was always kind of a hack. You have to multiply it by the "nominal" standard deviation, and that, too is a bit of a hack. Svel -- I don't know, we may have added it because someone wanted it. So we may have to put them back in for backward compatibility, but I think their use should be discouraged and new applications should use the HDF results file.

**Comment by emthompson-usgs** [comment]
Yeah, I agree and I don't really like the idea of including either of them but the ground-failure issue illustrates how taking them away could create headaches for users. If we successfully convince people (and ourselves) to use `shake_result.hdf` rather than `grid.xml` then the issue goes away. At the same time, I don't have time right now to make that change in the ground failure code.

**Comment by mhearne-usgs** [comment]
Well, fortunately you don't have to worry about until we go live with SM4.0 :)

It is generally true that we could be breaking all kinds of other people's stuff for every small change we make to ShakeMap output, so we have to decide if we want to be held hostage by that forever.

**Comment by emthompson-usgs** [comment]
This came up because I tried running the Puerto Rico event for Kristin with the Shakemap 4.0 grid.xml. So even though we aren't "live" with Shakemap 4.0, unexpected issues do come up.

**Comment by mhearne-usgs** [comment]
Just add svel (change to vs30)
