### ISSUE TITLE
Consider replacing event.xml with quakeml

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#567]
Or perhaps supporting both

**Comment by cbworden** [comment]
We can address this if and when there is a demand for it. There are parsers out there (e.g., https://gitext.gfz-potsdam.de/nooshiri/pyquakeml) so it shouldn't be too hard to implement. Still, we'd need examples of the proposed Quakeml input files to test with. Closing this for now, can revisit when there's a need.
