### ISSUE TITLE
Epsilon

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#574]
Possibly add a config option to specify epsilon, defined a the number of standard deviations away from the mean (in log space). Default would be zero (giving the mean). It might make more sense for this to be a shakecast issue since we provide the standard deviations also and so it is easy to do with the shakemap outputs.

**Comment by mhearne-usgs** [comment]
What is the context here? GMPE outputs? What is the use case for epsilon?

**Comment by emthompson-usgs** [comment]
Context is output IMT. We have a grid of means and standard deviations. Sometimes people want something like mean + 1 sigma or +2 sigma. I think it is usually shakecast users like NRC that want this.

**Comment by mhearne-usgs** [comment]
ShakeCast can do its own math with mean/std. @klin-usgs ?
