### ISSUE TITLE
Make sure all IMCs associated with GMPEs are covered by our conversions

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#580]
From: https://github.com/gem/oq-engine/blob/a47af0d1380bbb4051386d0c505591373f9d7ff4/openquake/hazardlib/const.py#L53

Turns out that not all of these IMCs are supported by our conversions - one case in particular is "VECTORIAL", which is needed by Atkinson2010, and not in list of supported IMCs in our implementations of either Boore&Kishida or Beyer&Bommer.

Heather will do initial research on those two papers to see if any of these IMCs are defined in the paper and not in our implementations.

**Comment by emthompson-usgs** [comment]
Not sure we need to do any research, just make the methods function as documented: 
https://github.com/usgs/shakemap/blob/master/shakelib/conversions/imc/boore_kishida_2017.py#L41
Any non-supported IMCs should be assumed to be GM.

**Comment by hschovanec-usgs** [comment]
Thank you for the info. Will look into this as soon as I finish up #549.
