### ISSUE TITLE
shakelib container api page is empty?

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#598]
https://usgs.github.io/shakelib/shakelib.utils.container.html

**Comment by cbworden** [comment]
Mike, that is the old, deprecated shakelib repository. The new documentation is part of the ShakeMap repo: https://usgs.github.io/shakemap/shakelib/shakelib.utils.containers.html

**Comment by mhearne-usgs** [comment]
Yes, but it is linked to from here: https://usgs.github.io/shakemap/manual4_0/tg_formats.html

I'll fix it.

**Comment by cbworden** [comment]
Removed code and docs from shakelib to avoid future confusion.
