### ISSUE TITLE
About Installation

### ISSUE THREAD

**Issue by Yajing-Zhao** [usgs/shakemap#618]
Hello,

I installed the shakemap as the procedure in Wiki, but the py.test . is not successful. I cannot figure out where is wrong.

Thanks!

The error is as follows:
Activate base virtual environment

CommandNotFoundError: 'activate is not a conda command.
Did you mean 'source activate'?

Creating the shakemap virtual environment:
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............
Solving package specifications: .
#
# To activate this environment, use:
# > source activate shakemap
#
# To deactivate an active environment, use:
# > source deactivate
#

Activating the shakemap virtual environment

CommandNotFoundError: 'activate is not a conda command.
Did you mean 'source activate'?

Installing shakemap...
Obtaining file:///zhome/fslcollab151/shakemap_src
Installing collected packages: shakemap
  Found existing installation: shakemap 0.6+778.ge8ffab0
    Uninstalling shakemap-0.6+778.ge8ffab0:
      Successfully uninstalled shakemap-0.6+778.ge8ffab0
  Running setup.py develop for shakemap
Successfully installed shakemap
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Type 'conda activate shakemap' to use this new virtual environment.
fslcollab151:shakemap_src$ conda activate shakemap

CommandNotFoundError: 'activate is not a conda command.
Did you mean 'source activate'?

fslcollab151:shakemap_src$ source activate shakemap
************************************************************

(shakemap) fslcollab151:shakemap_src$ py.test .
============================================ test session starts =============================================
platform linux -- Python 3.5.4, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /zhome/fslcollab151/shakemap_src, inifile:
plugins: cov-2.5.1
collected 1 item / 43 errors

=================================================== ERRORS ===================================================
______________________________ ERROR collecting tests/shakelib/distance_test.py ______________________________
ImportError while importing test module '/zhome/fslcollab151/shakemap_src/tests/shakelib/distance_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/distance_test.py:19: in <module>
    from shakelib.rupture.quad_rupture import QuadRupture
E   ImportError: No module named 'shakelib.rupture'
_____________________________ ERROR collecting tests/shakelib/multigmpe_test.py ______________________________
ImportError while importing test module '/zhome/fslcollab151/shakemap_src/tests/sha

**Comment by emthompson-usgs** [comment]
I believe that this is because you are running an old version of `conda`. If updating your conda install does not work, please send us the output of 
```
conda --version
```

**Comment by Yajing-Zhao** [comment]
(shakemap) fslcollab151:shakemap_src$ conda --version
conda 4.3.31

Thanks!

**Comment by emthompson-usgs** [comment]
Did you try to update? The latest version is 4.5. I believe that there were some major changes to how conda works after the version that you are using and so updating is necessary for it to work. We (@mhearne-usgs @cbworden) should probably add something to the installer that checks that the conda version is new enough.

**Comment by Yajing-Zhao** [comment]
I have updated the version of conda and installed the software again but the py.test is still not successful.
(shakemap) fslcollab151:shakemap_src$ conda --version
conda 4.5.4
(shakemap) fslcollab151:shakemap_src$ py.test .
============================================ test session starts =============================================
platform linux -- Python 3.5.4, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /zhome/fslcollab151/shakemap_src, inifile:
plugins: cov-2.5.1
collected 2 items / 42 errors

=================================================== ERRORS ===================================================
______________________________ ERROR collecting tests/shakelib/distance_test.py ______________________________
ImportError while importing test module '/zhome/fslcollab151/shakemap_src/tests/shakelib/distance_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/distance_test.py:19: in <module>
    from shakelib.rupture.quad_rupture import QuadRupture
E   ImportError: No module named 'shakelib.rupture'
_____________________________ ERROR collecting tests/shakelib/multigmpe_test.py

**Comment by emthompson-usgs** [comment]
I couldn't tell from the more recent log you sent, but did you use `conda activate shakemap` or `source activate shakemap` to get into the virtual environment? The latter should not work if you are using the new version of conda. 

Can you give us some more information about you system: 
What OS are you using? 
Did you install conda with miniconda or anaconda? 
What is the result of `which shake`?

**Comment by Yajing-Zhao** [comment]
I used conda activate shakemap.

(shakemap) fslcollab151:shakemap_src$ head -n 1 /etc/issue
Red Hat Enterprise Linux Server release 6.6 (Santiago)

I used anaconda.

(shakemap) fslcollab151:shakemap_src$ which shake
~/anaconda3/bin/shake

**Comment by mhearne-usgs** [comment]
Run the following set of commands from the shakemap_src directory:
"bash install.sh"
"conda activate shakemap"
"pip install -e ."
"py.test ."

The pip install should execute during the install script, but we have reports of that sometimes failing.

**Comment by Yajing-Zhao** [comment]
Ok, I will have a try.
Thanks a lot!

**Comment by leeselinaw** [comment]
Hello - I am trying to download shakemap, but the link (https://vault.gps.caltech.edu/repos/products/shakemap/tags/release-3.5/) seems to be broken.  I get this:  Not Found
The requested URL /repos/products/shakemap/tags/release-3.5/ was not found on this server.

Any help please?  THANKS!

**Comment by Yajing-Zhao** [comment]
Hello, I tried to install the software again, but it didn't work, the error is as follows.

************************************************
YJ:shakemap_src yajing$ bash install.sh
Path:
/Users/yajing/anaconda3/bin:/Users/yajing/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/yajing/Library/Python/2.7/bin/
NOTE: A non-interactive matplotlib backend (Agg) has been set for this user.
conda 4.5.4
conda detected, installing shakemap environment...
PATH:
/Users/yajing/anaconda3/bin:/Users/yajing/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/yajing/Library/Python/2.7/bin/

Activate base virtual environment
Creating the shakemap virtual environment:
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - fiona=1.7.11 -> gdal=2.2 -> libgdal==2.2.3 -> poppler=0.61 -> freetype=2.8
  - freetype=2.6.3
Use "conda info <package>" to see the dependencies for each package.

Failed to create conda environment.  Resolve any conflicts, then try again.
YJ:shakemap_src yajing$

**Comment by emthompson-usgs** [comment]
@leeselinaw This not related to this thread so I created a separate issue for it: #633.

**Comment by emthompson-usgs** [comment]
@Yajing-Zhao Thank you for the update. We have another user who also reported a compatibility problem with fiona and we are working on it. However, it looks like you have an old version of python (v2.7) in your path and that might be causing problems. It might be worth trying to remove it and trying again.

**Comment by Yajing-Zhao** [comment]
Thanks!
I have updated the version of python, but there is still the compatibility problem with fiona. Have you fixed it?

**Comment by emthompson-usgs** [comment]
@Yajing-Zhao I believe that pull request #635 should have fixed your issues. Please try again by cloning the current version of the repository and let us know how it goes.

**Comment by cbworden** [comment]
Seems resolved, so I'm closing.
