### ISSUE TITLE
Link to shakemap 3.5 repository is broken

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#633]
We are looking into this issue and do not yet know what the cause is or how to fix it.

**Comment by cbworden** [comment]
We continue to investigate this issue, and hope to have a resolution soon.

**Comment by cbworden** [comment]
This should be fixed now.

**Comment by leeselinaw** [comment]
Thank you @emthompson-usgs  for creating this new issue and thank you @cbworden for fixing the link! Much appreciated!
