### ISSUE TITLE
Mapping module complains about as_matrix()

### ISSUE THREAD

**Issue by cbworden** [usgs/shakemap#650]
Vince reports:
- Running ‘shake ci3144585 mapping’, I got the following warning:

INFO -- 2018-06-12 22:00:57 -- shake.main -- Running command mapping /Users/vinceq/miniconda2/envs/shakemap/lib/python3.5/site-packages/mapio/city.py:322: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  x,y = mbasemap(self._dataframe['lon'].as_matrix(),self._dataframe['lat'].as_matrix())

**Comment by mhearne-usgs** [comment]
Closed with version 0.7.9 of MapIO.
