### ISSUE TITLE
model flag for only running with observed or macroseismic data, or neither.

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#656]
Please describe your issue here:

Version: keywords are unexpanded, not using
got version from VCS {'full-revisionid': '3512c4b7fa593032d2d68005540890568e38d3ea', 'dirty': False, 'version': '0.7+50.g3512c4b', 'error': None}
Version: 0.7+50.g3512c4b
 full-revisionid: 3512c4b7fa593032d2d68005540890568e38d3ea
 dirty: False

uname: Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64

conda: conda 4.5.4

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
This would really be a flag to assemble.
