### ISSUE TITLE
Modify environment yml files to newest version of amptools

### ISSUE THREAD

**Issue by kmarano-usgs** [usgs/shakemap#663]
The current environment yml files are set to amptools 1.0.3. The version should be at least 1.1.0 to include newly added readers.

**Comment by mhearne-usgs** [comment]
We're currently not using the environment specific yml files in the installer, because they seemed to be causing more problems than they were solving.

**Comment by kmarano-usgs** [comment]
I made the initial issue because I figured that was the root of the problem I was having. Apparently, it wasn't. The issue is that the most recent version of ShakeMap doesn't install the most recent version of amptools. This may actually be an amptools problem and not ShakeMap. I'll make an issue over in that repository.
