### ISSUE TITLE
Failure of probs_test.py when running py.test

### ISSUE THREAD

**Issue by kmarano-usgs** [usgs/shakemap#664]
Output of test (excluding warnings):
================================================ test session starts =================================================
platform darwin -- Python 3.5.5, pytest-3.6.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/kmarano/shakemap_src, inifile:
plugins: cov-2.5.1
collected 127 items                                                                                                  

tests/shakelib/distance_test.py .....                                                                          [  3%]
tests/shakelib/multigmpe_test.py .............                                                                 [ 14%]
tests/shakelib/origin_test.py .                                                                                [ 14%]
tests/shakelib/rupture_test.py ............                                                                    [ 24%]
tests/shakelib/sites_test.py ..                                                                                [ 25%]
tests/shakelib/station_test.py .....                                                                           [ 29%]
tests/shakelib/virtualipe_test.py .                                                                            [ 30%]
tests/shakelib/conversions/imc/beyer_bommer_2006_test.py .                                                     [ 31%]
tests/shakelib/conversions/imc/boore_kishida_2017_test.py .                                                    [ 32%]
tests/shakelib/conversions/imt/bommer_alarcon_2006_test.py .                                                   [ 33%]
tests/shakelib/conversions/imt/newmark_hall_1982_test.py .                                                     [ 33%]
tests/shakelib/correlation/baker_jayaram_2008_test.py .                                                        [ 34%]
tests/shakelib/correlation/boore_2003_test.py .                                                                [ 35%]
tests/shakelib/correlation/goda_atkinson_2010_test.py .                                                        [ 36%]
tests/shakelib/correlation/loth_baker_2013_test.py .                                                           [ 37%]
tests/shakelib/directivity/bayless2013_test.py ......                                                          [ 41%]
tests/shakelib/directivity/rowshandel2013_test.py .....                                                        [ 45%]
tests/shakelib/gmice/ak07_test.py .                                                                            [ 46%]
tests/shakelib/gmice/wald99_test.py .                                                                          [ 47%]
tests/shakelib/gmice/wgrw12_test.py .                                                                          [ 48%]
tests/shakelib/plotting/plot_rupture_test.py ..                                                                [ 49%]
tests/shakelib/utils/container_test.py ....                                                                    [ 52%]
tests/shakelib/utils/geodetic_distance_test.py .                                                               [ 53%]
tests/shakelib/utils/str_imt_test.py .                                                                         [ 54%]
tests/shakelib/utils/utils_test.py .........                                                                   [ 61%]
tests/shakemap/coremods/assemble_augment_test.py ..                                                            [ 62%]
tests/shakemap/coremods/associate_test.py .                                                                    [ 63%]
tests/shakemap/coremods/cancel_test.py .                                                                       [ 64%]
tests/shakemap/coremods/contour_test.py .                                                                      [ 65%]
tests/shakemap/coremods/dyfi_test.py ..                                                                        [ 66%]
tests/shakemap/coremods/kml_test.py .                                                                          [ 67%]
tests/shakemap/coremods/model_test.py ...                                                                      [ 70%]
tests/shakemap/coremods/products_test.py .                                                                     [ 70%]
tests/shakemap/coremods/select_test.py .                                                                       [ 71%]
tests/shakemap/coremods/transfer_test.py .                                                                     [ 72%]
tests/shakemap/coremods/verification_test.py ...........                                                       [ 81%]
tests/shakemap/programs/profile_test.py .                                                                      [ 81%]
tests/shakemap/programs/shake_test.py .                                                                        [ 82%]
tests/shakemap/programs/sm_compare_test.py .                                                                   [ 83%]
tests/shakemap/utils/amps_test.py .                                                                            [ 84%]
tests/shakemap/utils/config_test.py .                                                                          [ 85%]
tests/shakemap/utils/dependency_test.py ...                                                                    [ 87%]
tests/shakemap/utils/generic_amp_test.py .                                                                     [ 88%]
tests/shakemap/utils/layer_test.py .                                                                           [ 88%]
tests/shakemap/utils/probs_test.py F                                                                           [ 89%]
tests/shakemap/utils/queue_test.py ........                                                                    [ 96%]
tests/shakemap/utils/utilssm_test.py .....                                                                     [100%]

====================================================== FAILURES ======================================================
_____________________________________________________ test_probs _____________________________________________________

    def test_probs():
        install_path, config_path = get_config_paths()
        config = ConfigObj(os.path.join(install_path, 'config', 'select.conf'))
        validate_config(config, install_path)
    
        #
        # Real event: M 6.9 - 151km SSW of Kokopo, Papua New Guinea
        # 2018-03-29 21:25:36 UTC
        # Note: slab model depth is 33.4638 km
        #
        datadir = os.path.join(
            homedir, '..', '..', 'data', 'eventdata', 'us1000db40', 'current')
        eventxml = os.path.join(datadir, 'event.xml')
        org = Origin.fromFile(eventxml)
        gmpe_list, weight_list, strec_results = get_weights(org, config)
        assert len(gmpe_list) == 1
        assert len(weight_list) == 1
        assert gmpe_list[0] == 'subduction_interface_nshmp2014'
        np.testing.assert_allclose(weight_list[0], 1.0, rtol=1e-05)
    
        # move hypo to the surface:
        org.depth = 0
        gmpe_list, weight_list, strec_results = get_weights(org, config)
        # dz is 33.4638
        # slab uncertainty is 10, so x2 in int|abs(dz) is 29
        # so m_{int|abs(dz)} = 0.15
        np.testing.assert_allclose(
            weight_list,
            np.array([0.85,  0.15]),
>           rtol=1e-05)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-05, atol=0
E       
E       (mismatch 100.0%)
E        x: array([0.400137, 0.599863])
E        y: array([0.85, 0.15])

tests/shakemap/utils/probs_test.py:45: AssertionError
------------------------------------------------ Captured stderr call ------------------------------------------------
DEBUG;2018-06-21 13:59:53;probs.get_weights;Testing
DEBUG;2018-06-21 13:59:54;probs.get_weights;gmpelist: ['subduction_interface_nshmp2014']
DEBUG;2018-06-21 13:59:54;probs.get_weights;weightlist: [1.]
DEBUG;2018-06-21 13:59:54;probs.get_weights;Testing
DEBUG;2018-06-21 13:59:54;probs.get_weights;gmpelist: ['subduction_crustal', 'subduction_interface_nshmp2014']
DEBUG;2018-06-21 13:59:54;probs.get_weights;weightlist: [0.40013657 0.59986343]
------------------------------------------------- Captured log call --------------------------------------------------
probs.py                    26 DEBUG    Testing
probs.py                    59 DEBUG    gmpelist: ['subduction_interface_nshmp2014']
probs.py                    60 DEBUG    weightlist: [1.]
probs.py                    26 DEBUG    Testing
probs.py                    59 DEBUG    gmpelist: ['subduction_crustal', 'subduction_interface_nshmp2014']
probs.py                    60 DEBUG    weightlist: [0.40013657 0.59986343]

**Comment by mhearne-usgs** [comment]
It is related to slab 2.0.  Since we can't distribute that data yet, the test results reflect using slab 1.0.
