### ISSUE TITLE
Modify station.py to handle new data file attributes

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#682]
Please describe your issue here:
Modify station.py to handle comp element with new attribute called "orientation", with possible values of "h" or "z".
---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
Closed by PR #688
