### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by dynaryu** [usgs/shakemap#709]
I've successfully installed following the instructions in the wiki. But I've got 19 errors while testing the code, which seems to be related to libgdal.20.dylib. 

(shakemap) ~/Projects/shakemap_src$ py.test .
===================================================== test session starts =====================================================
platform darwin -- Python 3.5.5, pytest-3.6.3, py-1.5.4, pluggy-0.6.0
rootdir: /Users/hyeuk/Projects/shakemap_src, inifile: pytest.ini
plugins: cov-2.5.1
collected 56 items / 19 errors                                                                                                

=========================================================== ERRORS ============================================================
______________________________________ ERROR collecting tests/shakelib/distance_test.py _______________________________________
ImportError while importing test module '/Users/hyeuk/Projects/shakemap_src/tests/shakelib/distance_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/distance_test.py:24: in <module>
    from shakelib.sites import Sites
shakelib/sites.py:6: in <module>
    from mapio.gmt import GMTGrid
../../anaconda2/envs/shakemap/lib/python3.5/site-packages/mapio/gmt.py:14: in <module>
    from .grid2d import Grid2D
../../anaconda2/envs/shakemap/lib/python3.5/site-packages/mapio/grid2d.py:12: in <module>
    from .gridbase import Grid
../../anaconda2/envs/shakemap/lib/python3.5/site-packages/mapio/gridbase.py:8: in <module>
    from .geodict import GeoDict
../../anaconda2/envs/shakemap/lib/python3.5/site-packages/mapio/geodict.py:5: in <module>
    from osgeo import osr
../../anaconda2/envs/shakemap/lib/python3.5/site-packages/osgeo/__init__.py:21: in <module>
    _gdal = swig_import_helper()
../../anaconda2/envs/shakemap/lib/python3.5/site-packages/osgeo/__init__.py:17: in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
../../anaconda2/envs/shakemap/lib/python3.5/imp.py:243: in load_module
    return load_dynamic(name, filename, file)
../../anaconda2/envs/shakemap/lib/python3.5/imp.py:343: in load_dynamic
    return _load(spec)
E   ImportError: dlopen(/Users/hyeuk/anaconda2/envs/shakemap/lib/python3.5/site-packages/osgeo/_gdal.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libpoppler.76.dylib
E     Referenced from: /Users/hyeuk/anaconda2/envs/shakemap/lib/libgdal.20.dylib
E     Reason: image not found
_____________________________________ ERROR collecting tests/shakemap/utils/probs_test.py _____________________________________
ImportError while importing test module '/Users/hyeuk/Projects/shakemap_src/tests/shakemap/utils/probs_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/probs_test.py:8: in <module>
    from shakemap.utils.probs import get_weights
shakemap/utils/probs.py:7: in <module>
    from strec.subtype import SubductionSelector
../../anaconda2/envs/shakemap/lib/python3.5/site-packages/strec/subtype.py:11: in <module>
    import fiona
../../anaconda2/envs/shakemap/lib/python3.5/site-packages/fiona/__init__.py:69: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
../../anaconda2/envs/shakemap/lib/python3.5/site-packages/fiona/collection.py:9: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/hyeuk/anaconda2/envs/shakemap/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libpoppler.76.dylib
E     Referenced from: /Users/hyeuk/anaconda2/envs/shakemap/lib/libgdal.20.dylib
E     Reason: image not found
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 19 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 19 error in 7.15 seconds ===================================================

(shakemap) ~/Projects/shakemap_src$ python setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'error': None, 'dirty': False, 'version': '0.9+7.g62d7f1d', 'full-revisionid': '62d7f1d4653d280321d50cd768c76a496cc095a4'}
Version: 0.9+7.g62d7f1d
 full-revisionid: 62d7f1d4653d280321d50cd768c76a496cc095a4
 dirty: False

(shakemap) ~/Projects/shakemap_src$ uname -v
Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64

(shakemap) ~/Projects/shakemap_src$ conda --version
conda 4.5.4

**Comment by emthompson-usgs** [comment]
Hi Hyeuk,
Thanks for the report. This is actually something we've been working on and struggling with already. I will report back to this issue when we eventually find a solution.

**Comment by emthompson-usgs** [comment]
@dynaryu Can you please do a `git pull` in your shakemap repository and then re run the install script and see if this works for you now? We mad esome changes that have fixed this problem on all of the systems that we can test on.

**Comment by dynaryu** [comment]
I'm so glad to report back to you that the error was fixed, and all the tests were passed successfully.
Thanks so much for your kind and prompt support.

**Comment by wald-usgs** [comment]
Hi Hyeuk,

 

Greetings from Golden! 

 

Thanks for the feedback. Bruce & Eric are doing a fantastic job. I hope all is well at GA. I’ll mention you’re in touch with Nico.

 

Cheers, 

 

David

 

-- 

David Wald, Ph.D.

U.S. Geological Survey, Golden, CO

wald@usgs.gov, (303) 273 8441

 

Adjunct Associate Professor of Geophysics

Colorado School of Mines
