### ISSUE TITLE
Test failure with layer_test.py

### ISSUE THREAD

**Issue by vinceq-usgs** [usgs/shakemap#711]
Pytest failed the test_layers() test. Output below. Did the layer definition change? Or the distance calculation?

$ pytest tests/shakemap/utils/layer_test.py
======================== test session starts =========================
platform darwin -- Python 3.5.5, pytest-3.6.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/vinceq/repos/shakemap_src, inifile: pytest.ini
plugins: cov-2.5.1
collected 1 item                                                     

tests/shakemap/utils/layer_test.py F                           [100%]

============================== FAILURES ==============================
____________________________ test_layers _____________________________

    def test_layers():
        data_path = get_data_path()
        layer_path = os.path.join(data_path, 'layers')
    
        elon = -117.0
        elat = 33.0
        layer_distances = get_layer_distances(elon, elat, layer_path)
        reference = {'japan': 7462.090628325871,
                     'california': 0.0,
                     'induced': 1578.3879076203307,
                     'taiwan': 9698.206101592557}
>       layers_equal(layer_distances, reference)

tests/shakemap/utils/layer_test.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

layer1 = {'california': 0.0, 'induced': 1578.3879076203307, 'japan': 7972.113861374339, 'taiwan': 11022.339157753582}
layer2 = {'california': 0.0, 'induced': 1578.3879076203307, 'japan': 7462.090628325871, 'taiwan': 9698.206101592557}

    def layers_equal(layer1, layer2):
        assert sorted(layer1.keys()) == sorted(layer2.keys())
>       assert np.allclose(sorted(layer1.values()), sorted(layer2.values()))
E       AssertionError: assert False
E        +  where False = <function allclose at 0x1138e7488>([0.0, 1578.3879076203307, 7972.113861374339, 11022.339157753582], [0.0, 1578.3879076203307, 7462.090628325871, 9698.206101592557])
E        +    where <function allclose at 0x1138e7488> = np.allclose
E        +    and   [0.0, 1578.3879076203307, 7972.113861374339, 11022.339157753582] = sorted(dict_values([11022.339157753582, 0.0, 7972.113861374339, 1578.3879076203307]))
E        +      where dict_values([11022.339157753582, 0.0, 7972.113861374339, 1578.3879076203307]) = <built-in method values of dict object at 0x11befc808>()
E        +        where <built-in method values of dict object at 0x11befc808> = {'california': 0.0, 'induced': 1578.3879076203307, 'japan': 7972.113861374339, 'taiwan': 11022.339157753582}.values
E        +    and   [0.0, 1578.3879076203307, 7462.090628325871, 9698.206101592557] = sorted(dict_values([9698.206101592557, 0.0, 7462.090628325871, 1578.3879076203307]))
E        +      where dict_values([9698.206101592557, 0.0, 7462.090628325871, 1578.3879076203307]) = <built-in method values of dict object at 0x11befc888>()
E        +        where <built-in method values of dict object at 0x11befc888> = {'california': 0.0, 'induced': 1578.3879076203307, 'japan': 7462.090628325871, 'taiwan': 9698.206101592557}.values

tests/shakemap/utils/layer_test.py:24: AssertionError
====================== 1 failed in 0.59 seconds ======================

**Comment by cbworden** [comment]
OpenQuake changed their code, which changed some of the answers we get for (absurdly) large distances when using the orthographic projection. Since we don't pin our versions to specific versions of the dependencies, this is kind of a retroactive failure. We've run into some other recent dependency issues, so I've made an RC3 release for you to test. It passed the tests as of this afternoon. What happens tomorrow is anyone's guess.

**Comment by vinceq-usgs** [comment]
Okay this works (for now!)
