### ISSUE TITLE
downloading global topo and vs30 files

### ISSUE THREAD

**Issue by dynaryu** [usgs/shakemap#712]
It might not be a significant issue, but it could be useful especially to one with a slow internet connection, if progress of downloading the two files is shown when sm_profile is executed. Also, it failed to download the files even after a couple of hours. In this case, I wonder if it's possible to get the files directly from web.

sm_profile -c default -a

Created profile: Profile: default 
	Install Path: /Users/hyeuk/shakemap_profiles/default/install
	Data Path: /Users/hyeuk/shakemap_profiles/default/data
Retrieving global topo and Vs30 files. This may take a minute...

**Comment by dynaryu** [comment]
Later I noticed that the files can be downloaded from the uses ftp site.

**Comment by emthompson-usgs** [comment]
Okay, it sounds like you got this sorted out then. The idea is to use the `-n` option for `sm_profile` and then download the files yourself. I will try to put the url for those files somewhere that is easier to find.
