### ISSUE TITLE
Handle magnitude and other limitations in GEM GMPEs

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#788]
I just saw this error for a scenario I created:

 File "/Users/mhearne/miniconda/envs/shakemap/lib/python3.5/site-packages/openquake/hazardlib/gsim/tavakoli_pezeshk_2005.py", line 136, in _compute_magnitude_scaling_term
    assert mag <= 8.5

we should probably search for other asserts in the GMPEs and find any other types of limitations, and then handle them in MultiGMPE.

**Comment by emthompson-usgs** [comment]
Or we can make GMPEs without those assert statements. This appears to be inconsistently used in the OQ GMPEs.

**Comment by cbworden** [comment]
Closed (for now) by #869. We may need to revisit this issue if/when we encounter new GMPE limitations.
