### ISSUE TITLE
Abort processing of events with no exposure on land

### ISSUE THREAD

**Issue by cbworden** [usgs/shakemap#807]

**Comment by emthompson-usgs** [comment]
I thought we were going to make this a shaking threshold on land rather than depend on PAGER, which makes the whole thing a bit circular.

**Comment by cbworden** [comment]
Yes, that's my intent -- if there's no land within the mapped area, we stop processing. I'm not sure how to do this gracefully, but basically model can determine if there's any land in the map, and if not, communicate that to shake somewhow.
