### ISSUE TITLE
Add support for external estimates of ground motions

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#818]
This is primarily to support construction of shakemaps from simulations.

**Comment by cbworden** [comment]
@mhearne-usgs @emthompson-usgs , I can work on this, but the question is what format of inputs do we want? SM3.5 used GMT grd files, but that seems outdated now. But HDF may be too difficult for some groups to generate. So how do we want this data formatted. Ideally we would get the mean/median and sigma for each IMT.

**Comment by cbworden** [comment]
This is effectively done now, via PR #970. We'll likely have to make tweaks to the input format as we try other simulations, or if a simulation supports standard deviations, etc.
