### ISSUE TITLE
Problem with station data

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#842]
See event usp0001ccv on dev.

**Comment by emthompson-usgs** [comment]
It actually also looks fishy on production: https://earthquake.usgs.gov/earthquakes/eventpage/usp0001ccv/shakemap/intensity
Note that the instruments look fine here, but the macroseismic values are all MMI V regardless of distance.

**Comment by dslosky-usgs** [comment]
The shakemap stations layer expects each station feature to have a `feature['properties']['intensity']` and uses that property to set the color and MMI for the station popup. It looks like this property is coming in as null or undefined in this case.

@kmarano-usgs saw this with some DYFI stations and thought it was a DYFI issue... but this is looking like it might actually be a shakemap issue

@vinceq-usgs @cbworden

**Comment by cbworden** [comment]
If a station has flagged components, or the computed intensity is flagged, or the station otherwise can't be converted to intensity, then the property will be set to null in the JSON. This should be expected to happen fairly frequently, so the software should handle it gracefully.

**Comment by cbworden** [comment]
Dave W. wants to make sure that the station is rendered as transparent rather than color-filled when this occurs.

**Comment by dslosky-usgs** [comment]
@cbworden Are all of the stations missing the "intensity" property flagged? If so, we can go ahead and make them all transparent

**Comment by vinceq-usgs** [comment]
This is DYFI data, is it? I don't have a record of this event from 1981 in DYFI.

**Comment by emthompson-usgs** [comment]
I think this issue is confined to Atlas events with non-DYFI macroseismic data. I'm going to remove this from the "Update 1" milestone since this isn't something that needs to be fixed for shakemap to be run in production for real events. The solution is probably to manually review all of the input files for Atlas.

**Comment by cbworden** [comment]
@mhearne-usgs @emthompson-usgs @dslosky-usgs , is this still an issue, and if so, what do we do we need to move toward resolution?

**Comment by cbworden** [comment]
I think this was resolved by @dslosky-usgs some time ago in the web code. At least no one has mentioned it in a couple of years, so I think it's a non-issue.
