### ISSUE TITLE
--debug and max_workers?

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#872]
If the --debug flag is on, should we set max_workers to zero regardless of what is configured? It is effectively impossible to debug with nonzero maxworkers and I often forget to set it to zero for debugging.

**Comment by cbworden** [comment]
The issue I see with this is that if one turns on the debug output to see what is going on, and the debug flag sets max_workers to zero, the problem may disappear, making it harder to diagnose process-related problems.

**Comment by emthompson-usgs** [comment]
Ok.
