### ISSUE TITLE
Make mapping more modular

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#887]
There is a need to add arbitrary text/symbols/shapes to maps. Rather than go down the path of adding conf files to control this, we think it would be better to refactor mapping so that it can be used as a function/method that returns an axes object that can then be modified with any matplotlib commands. 

For example, the `draw_intensity` method currently takes in an output container as an argument, as well as a number of other arguments that can be found in the conf files. The argument list can/should be trimmed down. It then returns a path to the PDF/JPG files that it creates. It would be better if it returned the axes objects, and then the business of writing it to a file could be handled in the `mapping` coremod.

**Comment by emthompson-usgs** [comment]
Remember to remove short-term fix code that was created in PR #888.

**Comment by raychani** [comment]
I have used shakemap 3.5 without topography.

so I had tried removing topography but it was not simple work.

I hope you consider this when modularize mapping.

Thanks
