### ISSUE TITLE
No macroseismic stations on map using sm_create

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#899]
When I use `sm_create` with event ak20419010 I get dyfi_dat.xml and instrumented_dat.json but far fewer macroseismic stations are now showing up on the map than what is on comcat. There are only about 50 DYFI stations when run with sm_create, but many more in comcat.

**Comment by mhearne-usgs** [comment]
This appears to be a discrepancy between the DYFI nresp criteria in SM3.5 and SM4.0 - our code is currently stripping off any DYFI data with fewer than three responses. Its hard to tell exactly, but it appears that the AK ShakeMap is using DYFI data with fewer than that.  There are some other discrepancies between the ShakeMap station data and DYFI data on the interactive map that should be sorted out.

**Comment by dslosky-usgs** [comment]
@mhearne-usgs let me know what's happening on the interactive map and I can investigate!

**Comment by wald-usgs** [comment]
I've not looked at the details, but AK ShakeMap is probably NOT running getdyfi. So, their DYFI data may be from taking our much earlier station xml file with DYFI in it.

**Comment by vinceq-usgs** [comment]
I asked Natalia and Matt(?) to send us a copy of the raw file so we can compare it.

**Comment by cbworden** [comment]
@mhearne-usgs is this still an issue?

**Comment by mhearne-usgs** [comment]
sm_create is doing what it was designed to do - at the time of this writing there are 47 or 49 DYFI results (depending on resolution) that have >= 3 responses. sm_create does NOT preserve the stationlist data from the online ShakeMap exactly. Instead, it grabs the stationlist data, splits it into:
1) instrumented data
2) macroseismic (not DYFI) data
3) DYFI data

The DYFI data is dropped, and the other two data sets are written out as separate files. sm_create then fetches the most recent DYFI data product that has the largest number of "stations" with at least 3 responses, then makes a separate file from that.
