### ISSUE TITLE
py.test failure on Centos (libstdc++.so.6: version `GLIBCXX_3.4.20' not found)

### ISSUE THREAD

**Issue by hadighasemi** [usgs/shakemap#902]
Hi Team,

I am trying to install ShakeMap4.0 on a Centos machine. Following the Wiki, installation went smoothly with no error message. However, when I try "py.test" I get 30 errors with key error message:

" libstdc++.so.6: version `GLIBCXX_3.4.20' not found"

Below are the outputs for the requested commands.

Any help would be much appreciated.

Cheers,
Hadi
-------------------------------------------------------------------------------------------------------------------------------------------
(shakemap) [centos@ip-172-31-23-131 shakemap_src]$ python setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'error': None, 'date': '2019-01-23T11:01:54-0700', 'version': '4.0.1+46.g79d5c94', 'dirty': False, 'full-revisionid': '79d5c949957e7a34754ec0dab6bd7834027f712c'}
Version: 4.0.1+46.g79d5c94
 full-revisionid: 79d5c949957e7a34754ec0dab6bd7834027f712c
 dirty: False
 date: 2019-01-23T11:01:54-0700
-------------------------------------------------------------------------------------------------------------------------------------------
(shakemap) [centos@ip-172-31-23-131 shakemap_src]$ uname -v
#1 SMP Mon May 21 23:36:36 UTC 2018
-------------------------------------------------------------------------------------------------------------------------------------------
(shakemap) [centos@ip-172-31-23-131 shakemap_src]$ conda --version
conda 4.5.12

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
Hi Hadi,

Yes, there’s a problem right now that we’re trying to catch up with (part of the consequences of the government shutdown). It isn’t just Centos. Conda forge has stopped supporting python 3.5 (kind of a surprise to us), and so we are trying to get ShakeMap (and our supporting repos) to run with 3.6 or 3.7 python. But at the same time, the C compiler situation has shifted dramatically, and we have to sort that out, as well. We hope to have a working version in the next day or two, but we’re a bit at the mercy of the Anaconda/conda/conda-forge folks. The capriciousness with which they major changes in the dependency system makes me question our choice of python. But we are committed now, so we will do the best we can.

Sorry about the mess, but we are in the same boat — none of our systems can get the latest code base working (except on Mac OSX).  I assure you, getting the ShakeMap distribution going again is our #1 priority.

Bruce

**Comment by acarapetis** [comment]
Hi Hadi, Bruce,

I've been fiddling with various conda package versions and it looks like I've managed to get the tests to pass (in miniconda python3.5) by installing `libgcc=5.2.0`, `libpoppler=0.65.0`, `gdal=2.2.4` from the default channel; so as a short-term fix it might be viable to just pin these versions (and maybe some others that I ended up with by coincidence - [here's my full package list](https://gist.github.com/acarapetis/6f739621ed53891380f8dd8e19721b40)).

Best of luck with getting everything running smoothly again - the shutdown sounds like no fun at all. Here's hoping you get more than the 3 weeks!

**Comment by emthompson-usgs** [comment]
@acarapetis Thanks for the info, but currently we prefer to try to get things to work in python 3.6 or newer because conda-forge is [no longer supporting python 3.5](https://conda-forge.org/docs/news_announce.html). This announcement was back in September but we didn't hear about it until this week. We are pretty close to having this worked out and we are also working on strategies for keeping the repository more current, which we hope will lead to more smooth maintenance in the future. The reality is that there's a lot that we are still learning in regards to python code management but hopefully we will get better at this with time.

**Comment by hadighasemi** [comment]
It works, Thanks! 
I will do some more testing using AU-data-configuration and will let you know if there is a problem.

Cheers
