### ISSUE TITLE
Switch import of dataframe_to_xml to impactutils

### ISSUE THREAD

**Issue by mhearne-usgs** [usgs/shakemap#907]
Please describe your issue here:
https://github.com/usgs/shakemap/blob/master/shakemap/coremods/dyfi.py#L9
https://github.com/usgs/earthquake-impact-utils/blob/master/impactutils/io/table.py
---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
Closed by PR #908.
