### ISSUE TITLE
Macroseismic Observation

### ISSUE THREAD

**Issue by cbworden** [usgs/shakemap#924]
Does anyone in the world, except us, know what a "macroseismic observation" is? Can we come up with a better term for the legends on our maps?

**Comment by wald-usgs** [comment]
How about simply "seismic intensity" or "reported intensity"?

**Comment by emthompson-usgs** [comment]
Rather than changing the terminology, what if we added a section to the manual discussing shakemap-specific terminology and definitions? Frankly, it might even be helpful for us as a reference because it is easy to get confused by some of these terms if you haven't thought about them in a while.
