### ISSUE TITLE
error on wald99

### ISSUE THREAD

**Issue by raychani** [usgs/shakemap#925]
When I use the Wald99 GMICE, there are errors in wald99.py or model.py.

I tried to fix the error, but I can't verify it.

This is the lines I've fixed in getPreferredMI;
from
        mmi_pga = self.getMIfromGM(df['PGA'], oqimt, dists, mag)
        mmi_pgv = self.getMIfromGM(df['PGV'], oqimt, dists, mag)
to
        mmi_pga, x = self.getMIfromGM(df['PGA'], oqimt, dists, mag)
        mmi_pgv, x = self.getMIfromGM(df['PGV'], oqimt, dists, mag)

It means that ignore the dmmi_damp in the getMIfromGM

How do you think about this?

**Comment by emthompson-usgs** [comment]
This is not an error. The Wald99 getMIfromGM method returns two arrays. See description here: http://usgs.github.io/shakemap/shakelib/shakelib.gmice.wald99.html

**Comment by cbworden** [comment]
I understand now the error you are reporting and I'll fix it, as well as add a test for that method. In the future, please include the specific error message you are getting so that we can understand the issue better. Thanks.
