### ISSUE TITLE
two test fails on ubuntu 18.04 

### ISSUE THREAD

**Issue by edwarzambrano** [usgs/shakemap#929]
Hello, I have installed shakemap and the time to run test.py . It fails in 2 tests:

tests/shakelib/rupture/rupture_test.py ..F..........                     [ 46%]
tests/shakemap/coremods/products_test.py .F                              [ 67%]

Here, it is the output completed: https://pastebin.com/4F4VjrdF

Somebody, can you assit with these issues

I appreciate your cooperation and assistance   

    - `python setup.py version`

running version
keywords are unexpanded, not using
got version from VCS {'version': '4.0.1+100.g01206e69', 'full-revisionid': '01206e695a8abc5bac015dcce55ebe9e8ff2f510', 'dirty': False, 'error': None, 'date': '2019-03-01T13:28:31-0700'}
Version: 4.0.1+100.g01206e69
 full-revisionid: 01206e695a8abc5bac015dcce55ebe9e8ff2f510
 dirty: False
 date: 2019-03-01T13:28:31-0700

    - `uname -v`
#49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019

    - `conda --version`
conda 4.5.12

**Comment by cbworden** [comment]
There was a recent change to the PS2FF dependency that is causing some tests to fail. We'll try to get it fixed Monday, but in the meantime, your ShakeMap install will probably function correctly. The failure in rupture_test.py is the result of the PS2FF change. The other error, in products_test.py is the result of your system not downloading the required geographic data files. Sometimes simply running the tests again will fix the problem. If it doesn't, you may need to talk with your IT people and see if there is a firewall or other network security protocol that is preventing cartopy from retrieving the coastlines and other data.

**Comment by cbworden** [comment]
Try updating ps2ff to 1.5.1 with conda update (use the --no-deps option to avoid any unnecessary changes to your environment. Make sure you have the latest version of the ShakeMap code, and then run the tests again.

**Comment by emthompson-usgs** [comment]
Closing since this issue is apparently no longer active.
