### ISSUE TITLE
a bug on getPreferredMI in wald99(GMICE)

### ISSUE THREAD

**Issue by raychani** [usgs/shakemap#931]
When I input data, there are some cases like "having PGA and no PGV".
in this event, there is a bug that calculate mmi incorrectly in the wald99.py

For example, some station has a accelerometer and no seismometer.
If the stations PGA is 35 (%g), the mmi_pga will over 5(about 6.7)
And the mmi should be 6.7 because there is no PGV input.

but the mmi of the stations is calculated to under 2.
The reason is mmi_pgv has value 1.0, and mmi_pga(6.7) and mmi_pgv(1.0) scaled to 1.x

the correct value of mmi_pgv would be nan,
but in the getMIfromGM input data converted from nan to 0, maybe at the line 116
(and no assigning other value)
and it clipped to 1.0 at the line 131

I insert following temporary code at line 66.

        mmi_pgv[mmi_pgv==1] = mmi_pga[mmi_pgv==1]
        mmi_pga[mmi_pga==1] = mmi_pgv[mmi_pga==1]

It means that if the mmi_pg? is 1 ( the correct value will be nan),
assign mmi from the other type of seismometer.

This result looks like correctly. but i can't sure it.

**Comment by emthompson-usgs** [comment]
Can you provide a minimal code example so that we can reproduce the bug?

**Comment by cbworden** [comment]
I think I understand the issue. I've made a fix, and it should be merged into the repo shortly. In the future, as Eric suggests, it would be helpful to have an example that demonstrates the problem.

**Comment by emthompson-usgs** [comment]
Also, I'll note that this is not an issue that we typically expect. The original post seems to imply that it is not possible to get PGV from accelerometers or PGA from seismometers, but this is not actually true. The only time I could imagine this issue coming up in reality is when incomplete input files are provided.
