### ISSUE TITLE
Missing fault description

### ISSUE THREAD

**Issue by lisucr** [usgs/shakemap#932]
On section 2.3.2.3.3 assemble in the ShakeMapV4.0 manual, there seems to be a lack of information. There is no link to the rupture file description. Would you please tell me where to find that information in order to input fault data?

"assemble then reads any files with a _dat.xml extension and assembles them into a station list. See ??? for a description of the data file format. Similarly, assmeble will read a file with the _fault.txt (or _fault.json) extension and process it as a specification of a finite rupture. See ??? for a description of the rupture file formats. Note: only one rupture file should be present in the event’s input directory. If more than one file exists, only the first (lexicographically) will we processed."

**Comment by emthompson-usgs** [comment]
Until my PR is merged, see here:
http://usgs.github.io/shakemap/manual4_0/tg_input_formats.html

**Comment by lisucr** [comment]
Thanks a lot!
