### ISSUE TITLE
International borders missing

### ISSUE THREAD

**Issue by lisucr** [usgs/shakemap#936]
The program is not drawing international country borders.

python setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'version': '4.0.1+118.gf69dd060', 'full-revisionid': 'f69dd0608b6641112835f5981c97adaac5cba5d3', 'dirty': False, 'error': None, 'date': '2019-03-14T12:34:59-0600'}
Version: 4.0.1+118.gf69dd060
 full-revisionid: f69dd0608b6641112835f5981c97adaac5cba5d3
 dirty: False
 date: 2019-03-14T12:34:59-0600

#48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019

conda 4.5.12

![test](https://user-images.githubusercontent.com/48763623/54779984-468d5080-4bde-11e9-872f-85660468e7ef.png)

**Comment by lisucr** [comment]
For the time being, I added this piece of code to mapmaker.py and got the borders.
    
    countries = cfeature.NaturalEarthFeature(
        category='cultural',
        name='admin_0_countries',
        scale='10m',
        facecolor='none')

    ax.add_feature(countries, edgecolor='black', zorder=BORDER_ZORDER)

**Comment by emthompson-usgs** [comment]
Thanks! We haven't had time to look into this issue yet. If you want, you can send in a pull request with this change and after we review/test it we can merge it. Otherwise, we can add this code ourselves eventually.

**Comment by cbworden** [comment]
@mhearne-usgs can you look at this? I thought we were getting the borders, but I've checked a couple of maps and maybe we aren't. If we do add the suggested code, we may need to escape it during tests like we did with the coastlines. Thanks.

**Comment by emthompson-usgs** [comment]
I'm trying to test this change but the tests aren't passing on my system after the last pull request and so I don't think I will be able to figure this out until tomorrow.

**Comment by lisucr** [comment]
@emthompson-usgs I added the code right after the following lines 

    ax.add_feature(states_provinces, edgecolor='black', zorder=BORDER_ZORDER)
    ax.add_feature(states_provinces, edgecolor='black', zorder=COAST_ZORDER)

in two parts of the program. I don't know whether that was the right thing to do. It was just a workaround that happened to work to get my map ready.

**Comment by emthompson-usgs** [comment]
@cbworden @mhearne-usgs 
It looks like we were trying to draw international borders with a configurable "borderfile":
https://github.com/usgs/shakemap/blob/master/shakemap/mapping/mapmaker.py#L1187
Was there are good reason for this? I think the method proposed by @lisucr seems preferable to me. 

Also, I think we should (and maybe need to) move the code that creates the geographic features into the CALLED_FROM_PYTEST if blocks so that it doesn't download the data. I will do that when I fix the if-statements so that they function outside of pytest.

**Comment by emthompson-usgs** [comment]
FYI, here's what the map would look like with the new borders as suggested by @lisucr. 
![us20005j32_intensity_new](https://user-images.githubusercontent.com/15928870/54832893-b1906300-4c82-11e9-920d-81c10d3b2052.jpg)

**Comment by lisucr** [comment]
Just a final thought on this issue. State/provinces are difficult to distinguish from international borders (right now they have same line width and color). Perhaps using a different color for state/provinces would  (IMHO) make a difference.

![ecuador2](https://user-images.githubusercontent.com/48763623/54834105-13ea6300-4c85-11e9-9361-31ccfbd0f1a7.png)

**Comment by emthompson-usgs** [comment]
I agree with this also. I'm just going to wait to make the changes to give others some time to comment since there may be a history that I am not aware of for why it is the way it currently is.

**Comment by cbworden** [comment]
@mhearne-usgs  can comment on this with more experience, but my recollection is that when we print anything other than country boundaries (except in the US and Canada), we may get nothing, we may get a reasonable number of states/provinces/whatever, or we may get a huge number of minor subdivisions akin to plotting counties in the US. It varies by country and just depends on the dataset that the boundaries are drawn from. But maybe with cartopy it isn't that bad anymore, I'm not sure.

**Comment by mhearne-usgs** [comment]
Well, we're currently drawing only state/province boundaries, so it's possible that drawing country boundaries will make it really obvious that some countries lack state boundaries, which may lead to questions, but I think we can deal with that. I say go ahead and draw country boundaries in some way that distinguishes them from state/province ones.

**Comment by cbworden** [comment]
I've deployed the latest code on the backup system. If everything runs okay, I'll deploy it on the production system.

**Comment by cbworden** [comment]
This is now deployed on the production system. Let me know if you spot any anomalies or other problems.
