### ISSUE TITLE
Test failed with sm_compare_test.py, missing "ne_10m_coastline.zip"

### ISSUE THREAD

**Issue by hzfmer** [usgs/shakemap#948]
Please describe your issue here:

It seems the database on NeaturalEarthData is not accessible now, so the script is missing "_ne_10m_coastline.zip_".  I don't know how long this will last, but it does make this test and some plotting scripts fail. 

#### It might be better if there is a back up server to store those files?
E.g. https://github.com/nvkelso/natural-earth-vector,
where data files are not stored as zip though.

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this repository and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
We are trying to make all of the tests run without accessing the NE site. I'll look into this issue and see if I can bypass the dependency.

**Comment by hzfmer** [comment]
Thanks!

Just want to make myself clear that the main code fails as well.
For example `shake ci3144585 mapping` throws tens of
"`DownloadWarning: Downloading: http://naciscdn.org/naturalearth/10m/physical/ne_10m_lakes.zi`" 
 without generating any maps except "_pin-thumbnail.png_".

**Comment by cbworden** [comment]
Understood. Following a code update I'm likely to push today, the modules 'model', 'mapping', and 'kml' will require access to the NE data (at least once) before they'll function properly. This situation is a consequence of our using Cartopy's NE interface which provides us with oceans, lakes, and political boundaries. I'm not sure that we can provide a backup -- it would be best if we could get the Cartopy folks to try backup sources when the primary ones fail. If NE becomes consistently unavailable, we (and Cartopy) will have to rethink our approach -- possibly using the GMT databases. We'd really like to avoid adding large quantities of geographic data to the repo.
