### ISSUE TITLE
Implement a converter of Earthworm gmew output stationList XML files to the ShakeMap 4.0 input format would be helpful

### ISSUE THREAD

**Issue by seismopaul** [usgs/shakemap#955]
The Earthworm gmew module outputs an XML file of instrumental pga/pgv etc for each station that recorded strong-motion data. This format file was used in ShakeMap 3.5 as input for the instrumental values, but I don't see any command line converter tool to bring the XML data into the json format necessary for ShakeMap 4.0. It would be nice to have such a tool and probably be easy to write given the StationList class in the shakelib

**Comment by cbworden** [comment]
ShakeMap 4.0 does not require JSON-formatted input files. We have added some optional features to the XML, but the XML files that work with ShakeMap 3.5 should also work with ShakeMap 4.0. ShakeMap outputs a JSON-formatted station list (which includes a great deal of other information) that may be used as input, but that format is not required, and we have no plans to deprecate or eliminate the existing XML format.
