### ISSUE TITLE
External ground motion values

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/shakemap#958]
We now need a mechanism for constructing shakemaps for ground motions that have been computed externally, such as via finite difference/finite element simulations. 

- How should the external ground motions be specified?
- What format can/should we support?
- Only pre-computed metrics, or do we also accept time histories?
- Extent will presumably be auto set to match that of the external grid. 
- Will typically need to convert to MMI. 
- Is it worth trying to support cross period interpolation? I think this wouldn't be straight forward unless we treated the simulations as "stations".

**Comment by cbworden** [comment]
I think you added code for external simulations sometime after this issue was made. If we need more sophisticated features, we can open new issues. I'm closing this for now.
