### ISSUE TITLE
Docker image for ShakeMap

### ISSUE THREAD

**Issue by dhowell-sed** [usgs/shakemap#961]
I'm not 100% sure if this qualifies as an issue but figured it would be easiest to share this here: 

As a part of our work at the Swiss Seismological Service, I created a simple docker image for running ShakeMap (currently configured to run the latest release). We don't have any plans for long-term support of this image, but feel free to fork our source repo/cannibalize the Dockerfile if you end up creating your own:

https://hub.docker.com/r/seddev/shakemap
https://github.com/swiss-seismological-service/shakemap-docker

Cheers,
Dorran Howell
dorran.howell@sed.ethz.ch

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by emthompson-usgs** [comment]
Thanks! We have been talking about doing something along this lines and I'm sure this will be helpful for us because none of us have experience/expertise with Docker.

**Comment by dslosky-usgs** [comment]
@klin-usgs has done some work on this for shakecast as well

**Comment by dhowell-sed** [comment]
No problem! Let us know if you have any questions or suggestions
