### ISSUE TITLE
The shakemap test fails in 45 times

### ISSUE THREAD

**Issue by edwarzambrano** [usgs/shakemap#962]
Please describe your issue here:

Hello, I have installed shakemap (it has several issues) and the time to run test.py . It fails in 45 tests:

`(shakemap) usuario@usuario-N551JK:~/shakemap_dev$ py.test .`
================== test session starts =========================================================================
platform linux -- Python 3.6.7, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
rootdir: /home/usuario/shakemap_dev, inifile: pytest.ini
plugins: faulthandler-1.5.0, cov-2.7.1
**collected 2 items / 45 errors**                                                                                                                                                                              

========================= ERRORS =========================================================================
_____________________________________________________________________________ ERROR collecting tests/shakelib/distance_test.py _____________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/distance_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/distance_test.py:18: in <module>
    from shakelib.distance import Distance
E   ModuleNotFoundError: No module named 'shakelib.distance'
____________________________________________________________________________ ERROR collecting tests/shakelib/multigmpe_test.py _____________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/multigmpe_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/multigmpe_test.py:32: in <module>
    from shakelib.conversions.imc.boore_kishida_2017 import BooreKishida2017
E   ModuleNotFoundError: No module named 'shakelib.conversions.imc.boore_kishida_2017'
______________________________________________________________________________ ERROR collecting tests/shakelib/sites_test.py _______________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/sites_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/sites_test.py:12: in <module>
    from shakelib.sites import Sites
E   ModuleNotFoundError: No module named 'shakelib.sites'
_____________________________________________________________________________ ERROR collecting tests/shakelib/station_test.py ______________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/station_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/station_test.py:14: in <module>
    from shakelib.station import StationList
E   ModuleNotFoundError: No module named 'shakelib.station'
____________________________________________________________________________ ERROR collecting tests/shakelib/virtualipe_test.py ____________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/virtualipe_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/virtualipe_test.py:16: in <module>
    from shakelib.distance import Distance
E   ModuleNotFoundError: No module named 'shakelib.distance'
________________________________________________________________ ERROR collecting tests/shakelib/conversions/imc/beyer_bommer_2006_test.py _________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/conversions/imc/beyer_bommer_2006_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/conversions/imc/beyer_bommer_2006_test.py:14: in <module>
    from shakelib.conversions.imc.beyer_bommer_2006 import BeyerBommer2006
E   ModuleNotFoundError: No module named 'shakelib.conversions.imc.beyer_bommer_2006'
________________________________________________________________ ERROR collecting tests/shakelib/conversions/imc/boore_kishida_2017_test.py ________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/conversions/imc/boore_kishida_2017_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/conversions/imc/boore_kishida_2017_test.py:14: in <module>
    from shakelib.conversions.imc.boore_kishida_2017 import BooreKishida2017
E   ModuleNotFoundError: No module named 'shakelib.conversions.imc.boore_kishida_2017'
_______________________________________________________________ ERROR collecting tests/shakelib/conversions/imt/bommer_alarcon_2006_test.py ________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/conversions/imt/bommer_alarcon_2006_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/conversions/imt/bommer_alarcon_2006_test.py:11: in <module>
    from shakelib.conversions.imt.bommer_alarcon_2006 import BommerAlarcon2006
E   ModuleNotFoundError: No module named 'shakelib.conversions.imt.bommer_alarcon_2006'
________________________________________________________________ ERROR collecting tests/shakelib/conversions/imt/newmark_hall_1982_test.py _________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/conversions/imt/newmark_hall_1982_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/conversions/imt/newmark_hall_1982_test.py:12: in <module>
    from shakelib.conversions.imt.newmark_hall_1982 import NewmarkHall1982
E   ModuleNotFoundError: No module named 'shakelib.conversions.imt.newmark_hall_1982'
________________________________________________________________________ ERROR collecting tests/shakelib/correlation/dummy_test.py _________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/correlation/dummy_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/correlation/dummy_test.py:6: in <module>
    from shakelib.correlation.dummy import DummyCorrelation
E   ModuleNotFoundError: No module named 'shakelib.correlation.dummy'
___________________________________________________________________ ERROR collecting tests/shakelib/correlation/loth_baker_2013_test.py ____________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/correlation/loth_baker_2013_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/correlation/loth_baker_2013_test.py:6: in <module>
    from shakelib.correlation.loth_baker_2013 import LothBaker2013
E   ModuleNotFoundError: No module named 'shakelib.correlation.loth_baker_2013'
_____________________________________________________________________ ERROR collecting tests/shakelib/directivity/bayless2013_test.py ______________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/directivity/bayless2013_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/directivity/bayless2013_test.py:17: in <module>
    from shakelib.rupture.origin import Origin
E   ModuleNotFoundError: No module named 'shakelib.rupture.origin'
____________________________________________________________________ ERROR collecting tests/shakelib/directivity/rowshandel2013_test.py ____________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/directivity/rowshandel2013_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/directivity/rowshandel2013_test.py:13: in <module>
    from shakelib.sites import Sites
E   ModuleNotFoundError: No module named 'shakelib.sites'
____________________________________________________________________________ ERROR collecting tests/shakelib/gmice/ak07_test.py ____________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/gmice/ak07_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/gmice/ak07_test.py:11: in <module>
    from shakelib.gmice.ak07 import AK07
E   ModuleNotFoundError: No module named 'shakelib.gmice.ak07'
___________________________________________________________________________ ERROR collecting tests/shakelib/gmice/wald99_test.py ___________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/gmice/wald99_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/gmice/wald99_test.py:8: in <module>
    from shakelib.gmice.wald99 import Wald99
E   ModuleNotFoundError: No module named 'shakelib.gmice.wald99'
___________________________________________________________________________ ERROR collecting tests/shakelib/gmice/wgrw12_test.py ___________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/gmice/wgrw12_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/gmice/wgrw12_test.py:11: in <module>
    from shakelib.gmice.wgrw12 import WGRW12
E   ModuleNotFoundError: No module named 'shakelib.gmice.wgrw12'
______________________________________________________________________ ERROR collecting tests/shakelib/plotting/plot_rupture_test.py _______________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/plotting/plot_rupture_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/plotting/plot_rupture_test.py:12: in <module>
    from shakelib.rupture.quad_rupture import QuadRupture
E   ModuleNotFoundError: No module named 'shakelib.rupture.quad_rupture'
__________________________________________________________________________ ERROR collecting tests/shakelib/rupture/origin_test.py __________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/rupture/origin_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/rupture/origin_test.py:13: in <module>
    from shakelib.rupture.origin import Origin
E   ModuleNotFoundError: No module named 'shakelib.rupture.origin'
_________________________________________________________________________ ERROR collecting tests/shakelib/rupture/rupture_test.py __________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/rupture/rupture_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/rupture/rupture_test.py:22: in <module>
    from shakelib.rupture.origin import Origin, read_moment_quakeml
E   ModuleNotFoundError: No module named 'shakelib.rupture.origin'
_________________________________________________________________________ ERROR collecting tests/shakelib/utils/container_test.py __________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/utils/container_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/utils/container_test.py:17: in <module>
    from shakelib.utils.containers import ShakeMapInputContainer
E   ModuleNotFoundError: No module named 'shakelib.utils.containers'
_____________________________________________________________________ ERROR collecting tests/shakelib/utils/geodetic_distance_test.py ______________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/utils/geodetic_distance_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/utils/geodetic_distance_test.py:7: in <module>
    from shakemap.c.clib import (geodetic_distance_fast,
E   ModuleNotFoundError: No module named 'shakemap.c'
__________________________________________________________________________ ERROR collecting tests/shakelib/utils/str_imt_test.py ___________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/utils/str_imt_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/utils/str_imt_test.py:3: in <module>
    from shakelib.utils.imt_string import oq_to_file, file_to_oq
E   ModuleNotFoundError: No module named 'shakelib.utils.imt_string'
___________________________________________________________________________ ERROR collecting tests/shakelib/utils/utils_test.py ____________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakelib/utils/utils_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakelib/utils/utils_test.py:12: in <module>
    from shakelib.utils.exception import ShakeLibException
E   ModuleNotFoundError: No module named 'shakelib.utils.exception'
____________________________________________________________________ ERROR collecting tests/shakemap/coremods/assemble_augment_test.py _____________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/assemble_augment_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/assemble_augment_test.py:8: in <module>
    from shakemap.utils.config import get_config_paths
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
________________________________________________________________________ ERROR collecting tests/shakemap/coremods/associate_test.py ________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/associate_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/associate_test.py:8: in <module>
    from shakemap.utils.config import get_config_paths
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
_________________________________________________________________________ ERROR collecting tests/shakemap/coremods/contour_test.py _________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/contour_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/contour_test.py:4: in <module>
    from shakelib.plotting.contour import getContourLevels
E   ModuleNotFoundError: No module named 'shakelib.plotting.contour'
__________________________________________________________________________ ERROR collecting tests/shakemap/coremods/dyfi_test.py ___________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/dyfi_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/dyfi_test.py:9: in <module>
    from shakemap.coremods.dyfi import _get_dyfi_dataframe
E   ModuleNotFoundError: No module named 'shakemap.coremods.dyfi'
___________________________________________________________________________ ERROR collecting tests/shakemap/coremods/kml_test.py ___________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/kml_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/kml_test.py:10: in <module>
    from shakemap.coremods.base import Contents
E   ModuleNotFoundError: No module named 'shakemap.coremods.base'
__________________________________________________________________________ ERROR collecting tests/shakemap/coremods/model_test.py __________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/model_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/model_test.py:8: in <module>
    from shakemap.utils.config import get_config_paths
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
________________________________________________________________________ ERROR collecting tests/shakemap/coremods/products_test.py _________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/products_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/products_test.py:17: in <module>
    from shakemap.utils.config import get_config_paths
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
_________________________________________________________________________ ERROR collecting tests/shakemap/coremods/select_test.py __________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/select_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/select_test.py:7: in <module>
    from shakemap.utils.config import get_config_paths
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
__________________________________________________________________________ ERROR collecting tests/shakemap/coremods/sleep_test.py __________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/sleep_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/sleep_test.py:6: in <module>
    from shakemap.coremods.sleep import SleepModule
E   ModuleNotFoundError: No module named 'shakemap.coremods.sleep'
______________________________________________________________________ ERROR collecting tests/shakemap/coremods/verification_test.py _______________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/coremods/verification_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/coremods/verification_test.py:7: in <module>
    from shakemap.utils.config import get_config_paths
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
_________________________________________________________________________ ERROR collecting tests/shakemap/mapping/mapmaker_test.py _________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/mapping/mapmaker_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/mapping/mapmaker_test.py:10: in <module>
    from shakemap.mapping.mapmaker import draw_map
E   ModuleNotFoundError: No module named 'shakemap.mapping.mapmaker'
__________________________________________________________________________ ERROR collecting tests/shakemap/programs/shake_test.py __________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/programs/shake_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/programs/shake_test.py:7: in <module>
    from shakemap.utils.config import get_config_paths
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
_______________________________________________________________________ ERROR collecting tests/shakemap/programs/sm_rupture_test.py ________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/programs/sm_rupture_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/programs/sm_rupture_test.py:8: in <module>
    from shakelib.rupture.factory import get_rupture
E   ModuleNotFoundError: No module named 'shakelib.rupture.factory'
____________________________________________________________________________ ERROR collecting tests/shakemap/utils/amps_test.py ____________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/utils/amps_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/amps_test.py:10: in <module>
    from shakemap.utils.config import get_config_paths
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
___________________________________________________________________________ ERROR collecting tests/shakemap/utils/config_test.py ___________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/utils/config_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/config_test.py:12: in <module>
    import shakemap.utils.config as config
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
_________________________________________________________________________ ERROR collecting tests/shakemap/utils/dependency_test.py _________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/utils/dependency_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/dependency_test.py:12: in <module>
    from shakemap.utils.dependencies import (sha_sum,
E   ModuleNotFoundError: No module named 'shakemap.utils.dependencies'
________________________________________________________________________ ERROR collecting tests/shakemap/utils/generic_amp_test.py _________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/utils/generic_amp_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/generic_amp_test.py:8: in <module>
    from shakemap.utils.generic_amp import get_generic_amp_factors
E   ModuleNotFoundError: No module named 'shakemap.utils.generic_amp'
___________________________________________________________________________ ERROR collecting tests/shakemap/utils/layer_test.py ____________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/utils/layer_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/layer_test.py:10: in <module>
    from shakemap.utils.layers import (get_layer_distances,
E   ModuleNotFoundError: No module named 'shakemap.utils.layers'
___________________________________________________________________________ ERROR collecting tests/shakemap/utils/macros_test.py ___________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/utils/macros_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/macros_test.py:6: in <module>
    from shakemap.utils.macros import get_macros
E   ModuleNotFoundError: No module named 'shakemap.utils.macros'
___________________________________________________________________________ ERROR collecting tests/shakemap/utils/probs_test.py ____________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/utils/probs_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/probs_test.py:7: in <module>
    from shakemap.utils.config import get_config_paths
E   ModuleNotFoundError: No module named 'shakemap.utils.config'
___________________________________________________________________________ ERROR collecting tests/shakemap/utils/queue_test.py ____________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/utils/queue_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/queue_test.py:16: in <module>
    import shakemap.utils.queue as queue
E   ModuleNotFoundError: No module named 'shakemap.utils.queue'
__________________________________________________________________________ ERROR collecting tests/shakemap/utils/utilssm_test.py ___________________________________________________________________________
ImportError while importing test module '/home/usuario/shakemap_dev/tests/shakemap/utils/utilssm_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/shakemap/utils/utilssm_test.py:9: in <module>
    from shakemap.utils.utils import (get_network_name,
E   ModuleNotFoundError: No module named 'shakemap.utils.utils'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 45 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================= 45 error in 3.09 seconds =========================================================================================

Somebody, can you assit with these issues

I appreciate your cooperation and assistance

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:

    - `python setup.py version`
(shakemap) usuario@usuario-N551JK:~/shakemap_dev$ python setup.py version
running version
keywords are unexpanded, not using
got version from VCS {'version': '4.0.1+181.gddf8d500', 'full-revisionid': 'ddf8d50007c45a46551bdc02e0b55237731196c9', 'dirty': False, 'error': None, 'date': '2019-05-18T08:15:57-0600'}
Version: 4.0.1+181.gddf8d500
 full-revisionid: ddf8d50007c45a46551bdc02e0b55237731196c9
 dirty: False
 date: 2019-05-18T08:15:57-0600

    - `uname -v`
(shakemap) usuario@usuario-N551JK:~/shakemap_dev$ uname -v
#54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019

    - `conda --version`
(shakemap) usuario@usuario-N551JK:~/shakemap_dev$ conda --version
conda 4.6.14

**Comment by emthompson-usgs** [comment]
The number of times that the tests fails is irrelevant. The fundamental problem is that you did not install shakemap successfully so it can't import any of the shakemap modules. I'm going to close this because you also have issue #960 open, which is the underlying problem for this issue.
