### ISSUE TITLE
Test fail: Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by sadalsuud** [usgs/shakemap#963]
I install shakemap and when I execute the test it reaches up to 34% and then in the terminal I see: 

```
'tests/shakelib/plotting/plot_rupture_test.py .Fatal Python error: Segmentation fault'
'Current thread 0x00007f04d24d3740 (most recent call first):'
----- trace error
'Segmentation fault (core dumped)'
```
I don't know that I do, somebody can help with this? Thanks. Here my env 

    - `python setup.py version`
```
running version
keywords are unexpanded, not using
got version from VCS {'version': '4.0.1+184.g26deabeb', 'full-revisionid': '26deabebc0e228c2d46cee8e8755466629e34d85', 'dirty': False, 'error': None, 'date': '2019-05-30T21:41:01-0600'}
Version: 4.0.1+184.g26deabeb
 full-revisionid: 26deabebc0e228c2d46cee8e8755466629e34d85
 dirty: False
 date: 2019-05-30T21:41:01-0600
```

    - `uname -v`
#54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019

    - `conda --version`
conda 4.6.14

**Comment by emthompson-usgs** [comment]
One thing that may help (potentially resolve the segfault, or allow python to report more meaningful errors) would be to turn off parallelization. This is set in two of the conf files in `shakemap/data`: `model.conf` and `products.conf`. In both of those files, set `max_workers = 0` in the appropriate sections (where and how to do this is described in the comments inside those files). If it still fails, send us the terminal log for just:
```
py.test tests/shakelib/plotting/plot_rupture_test.py
```
It is unlikely that we will be able to reproduce the error and so it will be difficult to debug remotely. 

But this is also not a very important test that is failing (the rupture plotting methods are very small convenience functions that are not used for any shakemap output). So you could also turn off those tests by simply deleting the file and if all of the other tests pass, then you should be fine.
