### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode...

### ISSUE THREAD

**Issue by lmateus** [usgs/shakemap#972]
Hi

in this moment I'm creating a shakemap profile and I selected the default profile, a few minutes later in the terminal show me this wrong.

Created profile: Profile: default
Install Path: /home/shakemap/shakemap_profiles/default/install
Data Path: /home/shakemap/shakemap_profiles/default/data
Retrieving global topo and Vs30 files. This may take a minute...
Done.
Configuring profile to use downloaded topo and vs30 files...
Traceback (most recent call last):
File "/home/shakemap/anaconda3/envs/shakemap/bin/sm_profile", line 7, in
exec(compile(f.read(), file, 'exec'))
File "/home/shakemap/shakemap_src/bin/sm_profile", line 426, in
main(parser, pargs)
File "/home/shakemap/shakemap_src/bin/sm_profile", line 337, in main
create(config, profile, args.accept, ppath, args.nogrids)
File "/home/shakemap/shakemap_src/bin/sm_profile", line 305, in create
replace(my_config, old_line, new_line)
File "/home/shakemap/shakemap_src/bin/sm_profile", line 39, in replace
for line in old_file:
File "/home/shakemap/anaconda3/envs/shakemap/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7034: ordinal not in range(128)

please, help me with this query.

regards.

**Comment by cbworden** [comment]
It's a little hard to tell what the exact problem is with you providing so little detail. But I assume you're using unicode characters in path or profile names somewhere. I've made a couple of changes that should resolve some issues of that type, but other problems are likely. Go ahead and get the latest version of the code from the repo and see if it solves your problem. If it doesn't, we're going to need more information about your environment, the command line you issued, etc.
