### ISSUE TITLE
MultiGMPE-OpenQuake v3.4+ Compatibility Issue

### ISSUE THREAD

**Issue by dhowell-sed** [usgs/shakemap#980]
Hi ShakeMap team,

We're attempting to use ShakeMap with newer versions of OpenQuake and encountered a minor bug. Since v3.4, OpenQuake converts all class attributes for classes inheriting from GroundShakingIntensityModel to a frozenset.  

This breaks the latest version of ShakeMap, which populates MultiGMPE.DEFINED_FOR_INTENSITY_MEASURE_TYPES by looping through the child GMPEs and getting the union of their various class properties as shown in the below lines:

    In shakemap.shakelib.multigmpe.py:
    [Line 575]  imts = [g.DEFINED_FOR_INTENSITY_MEASURE_TYPES for g in gmpes]
    [Line 576]  self.DEFINED_FOR_INTENSITY_MEASURE_TYPES = set.union(*imts)

With newer versions of OpenQuake this raises `TypeError: descriptor 'union' requires a 'set' object but received a 'frozenset'` since it is calling the set.union() method on frozensets.

Would it be possible to update this class to work with the newer version of openquake? I'm not sure if this would affect other parts of the code, but a simple fix could be to change line 575 in multigmpe.py to:

    imts = [set(g.DEFINED_FOR_INTENSITY_MEASURE_TYPES) for g in gmpes]

I'm happy to make a pull request if you all want, just let me know.

Thanks!
Dorran

---
If you are reporting a problem with running the code, please report the outputs from the following commands after cloning this reponsitory and running `install.sh`:
    - `python setup.py version`
    - `uname -v`
    - `conda --version`

**Comment by cbworden** [comment]
Thanks for the bug report. I'll address it shortly. I just need to make sure that the fix works for both old and new versions of OpenQuake. I can't see why it wouldn't, but you know how that goes...
