### ISSUE TITLE
Additional TypeErrors in MultiGMPE.from_list()

### ISSUE THREAD

**Issue by dhowell-sed** [usgs/shakemap#986]
As described in issue #980, newer versions of OpenQuake convert most GMPE class fields to a FrozenSet during class creation. It turns out there are additional fields accessed in shakelib.multigmpe.MultiGMPE.from_list() which have the same bug as in #980. 

These fields include basically anything calling `set.union(*SOME_FIELD)` on the fields from the individual GMPEs which comprise the MultiGMPE (e.g. self.REQUIRES_SITES_PARAMETERS, self.REQUIRES_RUPTURE_PARAMETERS, self.REQUIRES_DISTANCES).

Would it be possible to update the assignment of these fields in MultiGMPE.to_list()?

Also just FYI - something that might be worth thinking about is that the stated reason for OpenQuake switching to a FrozenSet was to avoid [some issues](https://github.com/gem/oq-engine/commit/1df72548040cd24ec722a4e9fc17a66278873e16#diff-137e34a9cafa351e3b6e0a34b23ae381) with using a mutable object for these fields.  It could make sense to also use the FrozenSet type for these fields dynamically constructed in the MultiGMPE factory method to stick with how OpenQuake is implementing things (though I suspect it is not all that important if MultiGMPE is not being used directly by OpenQuake).

Thanks and please let me know if there's anything I can help with!

Cheers,
Dorran

**Comment by cbworden** [comment]
Thanks for the bug report. I'm putting in a PR that should fix these issues. It should be merged into the master repo in a little while. Let me know if you run into any additional issues.

I'm not sure that the set vs. frozenset difference matters much to our use of multigmpe. It's mostly a matter of whether or not PGV is supported and making sure we supply all of the needed rupture, distance, and site parameters for the chosen set of gmpes. If we start producing more spectral periods we may have to revisit the issue (along with a lot of other things).
