### ISSUE TITLE
CommandNotFoundError during installation

### ISSUE THREAD

**Issue by dynaryu** [usgs/shakemap#988]
I've got a message related to conda during the installation on ubuntu 18.04 although I already have the conda base.
I guess it's related to the issue below:
https://github.com/conda/conda/issues/7980
I've fixed it by adding eval "$(conda shell.bash hook)" in the script as suggested above, but not sure whether it's the best solution or not.

(base) hyeuk@hyeuk-GA:~/Projects/shakemap_src$ bash ./install.sh 
Using python version 3.6
conda 4.7.10
conda detected, installing shakemap environment...
Installing packages from conda-forge
    if [ -f "/home/hyeuk/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/hyeuk/miniconda3/etc/profile.d/conda.sh"
Activate base virtual environment

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

    - `python setup.py version`
running version
keywords are unexpanded, not using
got version from VCS {'version': '4.0.2+44.g0bd74b5d.dirty', 'full-revisionid': '0bd74b5dd4e999f0d9d841e5c38dd92989a51997', 'dirty': True, 'error': None, 'date': '2019-08-01T11:11:33-0600'}
Version: 4.0.2+44.g0bd74b5d.dirty
 full-revisionid: 0bd74b5dd4e999f0d9d841e5c38dd92989a51997
 dirty: True
 date: 2019-08-01T11:11:33-0600

    - `uname -v`: 
#24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019
    - `conda --version`
conda 4.7.10

**Comment by cbworden** [comment]
This is a tough one to nail down. Our builds on Travis CI (which is an Ubuntu build as far as I can tell) don't encounter this problem. I'll try experimenting with the suggested fix -- if it doesn't hurt anything, I'll leave it in the install script.
